label: Profily
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Použiť
          reset_button_label: Reset
          exposed_sorts_label: 'Zoradiť podľa'
          sort_asc_label: Vzostupne
          sort_desc_label: Zostupne
      empty:
        area:
          content:
            value: 'Zatiaľ nie sú žiadne profily.'
      arguments:
        uid:
          exception:
            title: Všetky
        type:
          exception:
            title: Všetky
        status:
          exception:
            title: Všetky
      title: Profily
  user_page:
    display_title: 'Stránka používateľa'
