label: Platby
display:
  default:
    display_title: Predvolené
    display_options:
      title: Platby
      fields:
        amount__number:
          label: Platba
          separator: ', '
        refunded_amount__number:
          label: 'Vrátené:'
          separator: ', '
        avs_response_code_label:
          separator: ', '
        avs_response_code:
          label: 'Kód odpovede AVS'
          separator: ', '
        state:
          label: Stav
          separator: ', '
        payment_gateway:
          label: 'Platobná brána'
          separator: ', '
        authorized:
          label: Autorizované
          separator: ', '
        completed:
          label: Ukončená
          separator: ', '
        remote_id:
          label: 'Vzdialené ID'
          separator: ', '
        operations:
          label: Operácie
      exposed_form:
        options:
          submit_button: Použiť
          reset_button_label: Reset
          exposed_sorts_label: 'Zoradiť podľa'
          sort_asc_label: Vzostupne
          sort_desc_label: Zostupne
      arguments:
        order_id:
          exception:
            title: Všetky
  page_1:
    display_title: Strana
    display_options:
      menu:
        title: Platby
