label: Kupóny
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
          exposed_sorts_label: 'Zoradiť podľa'
          sort_asc_label: Vzostupne
          sort_desc_label: Zostupne
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: «
            last: »
          expose:
            items_per_page_label: 'Položky na stránku'
            items_per_page_options_all_label: '- Všetky -'
            offset_label: Ofset
      fields:
        code:
          label: Kód
          separator: ', '
        usage_limit:
          label: Využitie
          separator: ', '
        usage_limit_customer:
          label: 'Limit na zákazníka'
          separator: ', '
        operations:
          label: Operácie
      filters:
        code:
          expose:
            label: Kód
      title: Kupóny
      arguments:
        promotion_id:
          exception:
            title: Všetky
  page_1:
    display_title: Strana
