display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Použiť
          reset_button_label: Reset
          exposed_sorts_label: 'Zoradiť podľa'
          sort_asc_label: Vzostupne
          sort_desc_label: Zostupne
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: «
            last: »
          expose:
            items_per_page_label: 'Položky na stránku'
            items_per_page_options_all_label: '- Všetky -'
            offset_label: Ofset
      fields:
        nid:
          separator: ', '
        nothing:
          alter:
            text: Upraviť
        nothing_1:
          alter:
            text: Odstrániť
        title:
          label: Názov
          separator: ', '
        sp_dynamic:
          separator: ', '
        sp_dynamic_1:
          separator: ', '
        dropbutton:
          label: Operácie
      filters:
        title:
          expose:
            label: Názov
  block_1:
    display_title: Blok
