label: 'Položky objednávky'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Použiť
          reset_button_label: Reset
          exposed_sorts_label: 'Zoradiť podľa'
          sort_asc_label: Vzostupne
          sort_desc_label: Zostupne
      fields:
        title:
          label: Názov
          separator: ', '
        unit_price__number:
          label: 'Jednotková cena'
          separator: ', '
        quantity:
          label: Množstvo
          separator: ', '
        total_price__number:
          label: 'Celková cena'
          separator: ', '
      arguments:
        order_item_id:
          exception:
            title: Všetky
