display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Použiť
          reset_button_label: Reset
          exposed_sorts_label: 'Zoradiť podľa'
          sort_asc_label: Vzostupne
          sort_desc_label: Zostupne
      fields:
        quantity:
          separator: ', '
        purchased_entity:
          separator: ', '
        total_price__number:
          separator: ', '
      arguments:
        order_id:
          exception:
            title: Všetky
