label: Obchody
display:
  default:
    display_title: Master
    display_options:
      title: Obchody
      fields:
        commerce_store_bulk_form:
          action_title: 'S výberom'
        is_default:
          label: Predvolené
          separator: ', '
        name:
          label: Názov
          separator: ', '
        changed:
          label: Aktualizované
          separator: ', '
        type:
          label: Typ
          separator: ', '
        operations:
          label: Operácie
      pager:
        options:
          tags:
            next: 'nasledujúca ›'
            previous: '‹ predchádzajúca'
            first: '« prvá'
            last: 'posledná »'
          expose:
            items_per_page_label: 'Položky na stránku'
            items_per_page_options_all_label: '- Všetky -'
            offset_label: Ofset
      exposed_form:
        options:
          submit_button: Použiť
          reset_button_label: Reset
          exposed_sorts_label: 'Zoradiť podľa'
          sort_asc_label: Vzostupne
          sort_desc_label: Zostupne
      filters:
        type:
          expose:
            label: Typ
  page_1:
    display_title: Strana
