label: Produse
display:
  default:
    display_title: Expert
    display_options:
      exposed_form:
        options:
          submit_button: Filtru
          reset_button_label: Resetează
          exposed_sorts_label: 'Sortare după'
          sort_asc_label: Ascendent
          sort_desc_label: Descendent
      pager:
        options:
          expose:
            items_per_page_label: 'Elemente pe pagină'
            items_per_page_options_all_label: '- Toate -'
            offset_label: Decalaj
          tags:
            previous: '‹ anterior'
            next: 'următor ›'
            first: '« primul'
            last: 'ultimul »'
      fields:
        commerce_product_bulk_form:
          action_title: 'Cu cele selectate'
        title:
          label: Titlu
          separator: ', '
        type:
          label: Tip
          separator: ', '
        status:
          label: Stare
          settings:
            format_custom_true: Publicat
            format_custom_false: Nepublicat
          separator: ', '
        changed:
          label: Actualizat
          separator: ', '
        operations:
          label: Operațiuni
      filters:
        type:
          expose:
            label: Tip
        title:
          expose:
            label: Titlu
      title: Produse
  page_1:
    display_title: Pagina
