label: Plăți
display:
  default:
    display_title: Implicit
    display_options:
      title: Plăți
      fields:
        amount__number:
          label: Plată
          separator: ', '
        refunded_amount__number:
          separator: ', '
        avs_response_code_label:
          separator: ', '
        avs_response_code:
          separator: ', '
        state:
          label: Status
          separator: ', '
        payment_gateway:
          label: 'Portal plată'
          separator: ', '
        authorized:
          label: Autorizat
          separator: ', '
        completed:
          label: Finalizată
          separator: ', '
        remote_id:
          label: 'ID de la distanță'
          separator: ', '
        operations:
          label: Operațiuni
      exposed_form:
        options:
          submit_button: Aplică
          reset_button_label: Resetează
          exposed_sorts_label: 'Sortare după'
          sort_asc_label: Ascendent
          sort_desc_label: Descendent
      arguments:
        order_id:
          exception:
            title: Toate
  page_1:
    display_title: Pagina
    display_options:
      menu:
        title: Plăți
