display:
  default:
    display_title: Expert
    display_options:
      exposed_form:
        options:
          submit_button: Filtru
          reset_button_label: Resetează
          exposed_sorts_label: 'Sortare după'
          sort_asc_label: Ascendent
          sort_desc_label: Descendent
      pager:
        options:
          expose:
            items_per_page_label: 'Elemente pe pagină'
            items_per_page_options_all_label: '- Toate -'
            offset_label: Decalaj
          tags:
            previous: '‹ anterior'
            next: 'următor ›'
            first: '« primul'
            last: 'ultimul »'
      fields:
        commerce_order_bulk_form:
          action_title: 'Cu cele selectate'
        type:
          label: Tip
          separator: ', '
        store_id:
          label: Magazin
          separator: ', '
        uid:
          label: Client
          separator: ', '
        mail:
          label: email
          separator: ', '
        total_price__number:
          label: Total
          separator: ', '
        changed:
          label: Actualizat
          separator: ', '
        operations:
          label: Operațiuni
      filters:
        type:
          expose:
            label: Tip
  page_1:
    display_title: Pagina
