label: Cupoane
display:
  default:
    display_title: Expert
    display_options:
      exposed_form:
        options:
          submit_button: Filtru
          reset_button_label: Resetează
          exposed_sorts_label: 'Sortare după'
          sort_asc_label: Ascendent
          sort_desc_label: Descendent
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« Primul'
            last: 'Ultimul »'
          expose:
            items_per_page_label: 'Elemente pe pagină'
            items_per_page_options_all_label: '- Toate -'
            offset_label: Decalaj
      fields:
        code:
          label: Cod
          separator: ', '
        usage_limit:
          label: Utilizare
          separator: ', '
        usage_limit_customer:
          separator: ', '
        operations:
          label: Operațiuni
      filters:
        code:
          expose:
            label: Cod
      title: Cupoane
      arguments:
        promotion_id:
          exception:
            title: Toate
  page_1:
    display_title: Pagina
