display:
  default:
    display_title: Expert
    display_options:
      exposed_form:
        options:
          submit_button: Aplică
          reset_button_label: Resetează
          exposed_sorts_label: 'Sortare după'
          sort_asc_label: Ascendent
          sort_desc_label: Descendent
      pager:
        options:
          tags:
            previous: '‹ Anterior'
            next: 'Următor ›'
            first: '« Primul'
            last: 'Ultimul »'
          expose:
            items_per_page_label: 'Elemente pe pagină'
            items_per_page_options_all_label: '- Toate -'
            offset_label: Decalaj
      fields:
        order_id:
          label: ID
          separator: ', '
        order_number:
          label: 'Număr comandă'
          separator: ', '
        placed:
          label: Data
          separator: ', '
        total_price__number:
          label: Total
          separator: ', '
        state:
          label: Status
          separator: ', '
      title: Comenzi
      arguments:
        uid:
          exception:
            title: Toate
  order_page:
    display_options:
      menu:
        title: Comenzi
