label: Magazine
display:
  default:
    display_title: Expert
    display_options:
      title: Magazine
      fields:
        commerce_store_bulk_form:
          action_title: 'Cu cele selectate'
        is_default:
          label: Implicit
          separator: ', '
        name:
          label: Nume
          separator: ', '
        changed:
          label: Actualizat
          separator: ', '
        type:
          label: Tip
          separator: ', '
        operations:
          label: Operațiuni
      pager:
        options:
          tags:
            next: 'următor ›'
            previous: '‹ anterior'
            first: '« primul'
            last: 'ultimul »'
          expose:
            items_per_page_label: 'Elemente pe pagină'
            items_per_page_options_all_label: '- Toate -'
            offset_label: Decalaj
      exposed_form:
        options:
          submit_button: Aplică
          reset_button_label: Resetează
          exposed_sorts_label: 'Sortare după'
          sort_asc_label: Ascendent
          sort_desc_label: Descendent
      filters:
        type:
          expose:
            label: Tip
  page_1:
    display_title: Pagina
