label: Profile
display:
  default:
    display_title: Expert
    display_options:
      exposed_form:
        options:
          submit_button: Aplică
          reset_button_label: Resetează
          exposed_sorts_label: 'Sortare după'
          sort_asc_label: Ascendent
          sort_desc_label: Descendent
      arguments:
        uid:
          exception:
            title: Toate
        type:
          exception:
            title: Toate
        status:
          exception:
            title: Toate
      title: Profile
