display:
  default:
    display_title: Expert
    display_options:
      exposed_form:
        options:
          submit_button: Aplică
          reset_button_label: Resetează
          exposed_sorts_label: 'Sortare după'
          sort_asc_label: Ascendent
          sort_desc_label: Descendent
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« Primul'
            last: 'Ultimul »'
          expose:
            items_per_page_label: 'Elemente pe pagină'
            items_per_page_options_all_label: '- Toate -'
            offset_label: Decalaj
      fields:
        nid:
          separator: ', '
        delta:
          format_plural_string: !!binary MQNAY291bnQ=
        nothing:
          alter:
            text: Editați
        nothing_1:
          alter:
            text: Șterge
        title:
          label: Titlu
          separator: ', '
        sp_dynamic:
          separator: ', '
        sp_dynamic_1:
          separator: ', '
        dropbutton:
          label: Operațiuni
      filters:
        title:
          expose:
            label: Titlu
  block_1:
    display_title: Bloc
