display:
  default:
    display_title: Principale
    display_options:
      exposed_form:
        options:
          submit_button: Applica
          reset_button_label: Ripristina
          exposed_sorts_label: 'Ordina per'
          sort_desc_label: Disc
      pager:
        options:
          tags:
            first: '« Prima'
            last: 'Ultima »'
          expose:
            items_per_page_label: 'Voci per pagina'
            items_per_page_options_all_label: '- Tutto -'
            offset_label: Scostamento
      fields:
        nothing:
          alter:
            text: Modifica
        nothing_1:
          alter:
            text: Elimina
        title:
          label: Titolo
        dropbutton:
          label: Operazioni
      filters:
        title:
          expose:
            label: Titolo
