display:
  default:
    display_title: Predefinito
    display_options:
      fields:
        completed:
          label: Completato
        operations:
          label: Operazioni
      exposed_form:
        options:
          submit_button: Applica
          reset_button_label: Ripristina
          exposed_sorts_label: 'Ordina per'
          sort_desc_label: Disc
      arguments:
        order_id:
          exception:
            title: Tutti
  page_1:
    display_title: Pagina
