display:
  default:
    display_title: Predefinito
    display_options:
      exposed_form:
        options:
          submit_button: Applica
          reset_button_label: Ripristina
          exposed_sorts_label: 'Ordina per'
          sort_desc_label: Disc
      pager:
        options:
          tags:
            first: '« Prima'
            last: 'Ultima »'
          expose:
            items_per_page_label: 'Voci per pagina'
            items_per_page_options_all_label: '- Tutto -'
            offset_label: Scostamento
      fields:
        name:
          label: Nome
        operations:
          label: Operazioni
      filters:
        name:
          expose:
            label: Nome
        status:
          expose:
            label: Stato
  admin:
    display_title: Pagina
    display_options:
      menu:
        title: Elenco
      tab_options:
        title: Elenco
