label: Media
display:
  default:
    display_title: Predefinito
    display_options:
      title: Media
      fields:
        media_bulk_form:
          action_title: Azione
        bundle:
          label: Tipo
        uid:
          label: Autore
        status:
          label: Stato
          settings:
            format_custom_false: 'Non pubblicato'
            format_custom_true: Pubblicato
        changed:
          label: Aggiornato
        operations:
          label: Operazioni
      pager:
        options:
          tags:
            first: '« Prima'
            last: 'Ultima »'
          expose:
            items_per_page_label: 'Voci per pagina'
            items_per_page_options_all_label: '- Tutto -'
            offset_label: Scostamento
      exposed_form:
        options:
          reset_button_label: Ripristina
          exposed_sorts_label: 'Ordina per'
          sort_desc_label: Disc
      filters:
        bundle:
          expose:
            label: Tipo
        status:
          group_info:
            label: 'Stato pubblicazione'
            group_items:
              1:
                title: Pubblicato
              2:
                title: 'Non pubblicato'
        langcode:
          expose:
            label: Lingua
  media_page_list:
    display_title: Media
    display_options:
      menu:
        title: Media
