display:
  default:
    display_title: Predefinito
    display_options:
      fields:
        comment_bulk_form:
          action_title: Azione
        name:
          label: Autore
        changed:
          label: Aggiornato
        operations:
          label: Operazioni
      pager:
        options:
          expose:
            items_per_page_label: 'Voci per pagina'
            items_per_page_options_all_label: '- Tutto -'
            offset_label: Scostamento
      exposed_form:
        options:
          reset_button_label: Ripristina
          exposed_sorts_label: 'Ordina per'
          sort_desc_label: Disc
      filters:
        langcode:
          expose:
            label: Lingua
  page_unapproved:
    display_options:
      fields:
        comment_bulk_form:
          action_title: Azione
        name:
          label: Autore
        changed:
          label: Aggiornato
        operations:
          label: Operazioni
      filters:
        langcode:
          expose:
            label: Lingua
