display:
  default:
    display_title: Principale
    display_options:
      exposed_form:
        options:
          submit_button: Applica
          reset_button_label: Ripristina
          exposed_sorts_label: 'Ordina per'
          sort_desc_label: Disc
      fields:
        title:
          label: Titolo
      arguments:
        order_item_id:
          exception:
            title: Tutti
