display:
  default:
    display_title: Principale
    display_options:
      exposed_form:
        options:
          reset_button_label: Ripristina
          exposed_sorts_label: 'Ordina per'
          sort_desc_label: Disc
      pager:
        options:
          tags:
            first: '« Prima'
            last: 'Ultima »'
          expose:
            items_per_page_label: 'Voci per pagina'
            items_per_page_options_all_label: '- Tutto -'
            offset_label: Scostamento
      fields:
        code:
          label: Codice
        operations:
          label: Operazioni
      filters:
        code:
          expose:
            label: Codice
      arguments:
        promotion_id:
          exception:
            title: Tutti
  page_1:
    display_title: Pagina
