display:
  default:
    display_title: Predefinito
    display_options:
      exposed_form:
        options:
          submit_button: Applica
          reset_button_label: Ripristina
          exposed_sorts_label: 'Ordina per'
          sort_desc_label: Disc
      empty:
        area_text_custom:
          content: 'Nessun contenuto disponibile.'
