label: Media
display:
  default:
    display_title: Bawaan
    display_options:
      title: Media
      fields:
        media_bulk_form:
          action_title: Tindakan
        bundle:
          label: Jenis
        uid:
          label: Penulis
        status:
          label: Status
          settings:
            format_custom_false: 'Tidak dipublikasikan'
            format_custom_true: Dipublikasikan
        changed:
          label: Diperbaharui
        operations:
          label: Operasi-operasi
      pager:
        options:
          tags:
            first: '« Pertama'
            last: 'Terakhir »'
          expose:
            items_per_page_label: 'Jumlah item per halaman'
            items_per_page_options_all_label: '- Semua -'
            offset_label: Letak
      exposed_form:
        options:
          reset_button_label: Reset
          exposed_sorts_label: 'Sortir dengan'
          sort_asc_label: 'Urutan turun'
      filters:
        bundle:
          expose:
            label: Jenis
        status:
          group_info:
            label: 'Status diterbitkan'
            group_items:
              1:
                title: Dipublikasikan
              2:
                title: 'Tidak dipublikasikan'
        langcode:
          expose:
            label: Bahasa
  media_page_list:
    display_title: Media
    display_options:
      menu:
        title: Media
