display:
  default:
    display_title: Bawaan
    display_options:
      fields:
        title:
          label: Judul
        type:
          label: 'Jenis konten'
        name:
          label: Penulis
        changed:
          label: Diperbaharui
        operations:
          label: Operasi-operasi
      pager:
        options:
          tags:
            first: '« Pertama'
            last: 'Terakhir »'
          expose:
            items_per_page_label: 'Jumlah item per halaman'
            items_per_page_options_all_label: '- Semua -'
            offset_label: Letak
      exposed_form:
        options:
          reset_button_label: Reset
          exposed_sorts_label: 'Sortir dengan'
          sort_asc_label: 'Urutan turun'
      filters:
        title:
          expose:
            label: Judul
        type:
          expose:
            label: 'Jenis konten'
        langcode:
          expose:
            label: Bahasa
