display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
          exposed_sorts_label: 'Sortir dengan'
          sort_asc_label: 'Urutan turun'
      pager:
        options:
          expose:
            items_per_page_label: 'Jumlah item per halaman'
            items_per_page_options_all_label: '- Semua -'
            offset_label: Letak
      fields:
        type:
          label: Jenis
        changed:
          label: Diperbaharui
        operations:
          label: Operasi-operasi
      filters:
        type:
          expose:
            label: Jenis
  page_1:
    display_title: Halaman
