display:
  default:
    display_title: Bawaan
    display_options:
      fields:
        type:
          label: Jenis
        timestamp:
          label: Tanggal
        message:
          label: Pesan
        name:
          label: Pengguna
        link:
          label: Operasi-operasi
      pager:
        options:
          expose:
            items_per_page_label: 'Jumlah item per halaman'
            items_per_page_options_all_label: '- Semua -'
            offset_label: Letak
      exposed_form:
        options:
          reset_button_label: Reset
          exposed_sorts_label: 'Sortir dengan'
          sort_asc_label: 'Urutan turun'
      filters:
        type:
          expose:
            label: Jenis
  page:
    display_title: Halaman
