label: 'Anggota grup'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Terapkan
          reset_button_label: Reset
          exposed_sorts_label: 'Sortir dengan'
          sort_asc_label: 'Urutan turun'
      pager:
        options:
          tags:
            first: '« Pertama'
            last: 'Terakhir »'
          expose:
            items_per_page_label: 'Jumlah item per halaman'
            items_per_page_options_all_label: '- Semua -'
            offset_label: Letak
      fields:
        name:
          label: Pengguna
        group_roles:
          label: Peran
        changed:
          label: Diperbaharui
        created:
          label: Bergabung
        dropbutton:
          label: Operasi-operasi
      arguments:
        gid:
          exception:
            title: Semua
      title: Anggota
  page_1:
    display_title: Halaman
    display_options:
      menu:
        title: Anggota
