display:
  default:
    display_title: Bawaan
    display_options:
      exposed_form:
        options:
          submit_button: Terapkan
          reset_button_label: Reset
          exposed_sorts_label: 'Sortir dengan'
          sort_asc_label: 'Urutan turun'
      pager:
        options:
          tags:
            first: '« Pertama'
            last: 'Terakhir »'
          expose:
            items_per_page_label: 'Jumlah item per halaman'
            items_per_page_options_all_label: '- Semua -'
            offset_label: Letak
      fields:
        name:
          label: Nama
        operations:
          label: Operasi-operasi
      filters:
        name:
          expose:
            label: Nama
        status:
          expose:
            label: Status
  admin:
    display_title: Halaman
    display_options:
      menu:
        title: Daftar
      tab_options:
        title: Daftar
