display:
  default:
    display_title: Bawaan
    display_options:
      title: Media
      fields:
        media_bulk_form:
          action_title: Tindakan
      pager:
        options:
          expose:
            items_per_page_label: 'Jumlah item per halaman'
            items_per_page_options_all_label: '- Semua -'
            offset_label: Letak
      exposed_form:
        options:
          reset_button_label: Reset
          exposed_sorts_label: 'Sortir dengan'
          sort_asc_label: 'Urutan turun'
      filters:
        status:
          group_info:
            label: Dipublikasikan
            group_items:
              1:
                title: Dipublikasikan
              2:
                title: 'Tidak dipublikasikan'
        name:
          expose:
            label: Nama
        langcode:
          expose:
            label: Bahasa
  page:
    display_title: Halaman
    display_options:
      fields:
        media_bulk_form:
          action_title: Tindakan
        edit_media:
          text: Sunting
        delete_media:
          text: Hapus
  widget:
    display_title: Piranti
    display_options:
      arguments:
        bundle:
          exception:
            title: Semua
      filters:
        name:
          expose:
            label: Nama
  widget_table:
    display_options:
      fields:
        name:
          label: Nama
        uid:
          label: Penulis
        changed:
          label: Diperbaharui
      arguments:
        bundle:
          exception:
            title: Semua
      filters:
        name:
          expose:
            label: Nama
