display:
  default:
    display_title: Bawaan
    display_options:
      fields:
        user_bulk_form:
          label: 'Pemutakhiran masal'
        name:
          label: 'Nama pengguna'
        status:
          label: Status
          settings:
            format_custom_true: Aktif
        roles_target_id:
          label: Peran
        operations:
          label: Operasi-operasi
      pager:
        options:
          tags:
            first: '« Pertama'
            last: 'Terakhir »'
          expose:
            items_per_page_label: 'Jumlah item per halaman'
            items_per_page_options_all_label: '- Semua -'
            offset_label: Letak
      exposed_form:
        options:
          reset_button_label: Reset
          exposed_sorts_label: 'Sortir dengan'
          sort_asc_label: 'Urutan turun'
      filters:
        status:
          group_info:
            label: Status
            group_items:
              1:
                title: Aktif
        roles_target_id:
          expose:
            label: Peran
        permission:
          expose:
            label: Kewenangan
  page_1:
    display_title: Halaman
    display_options:
      menu:
        title: Daftar
