display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Terapkan
          reset_button_label: Reset
          exposed_sorts_label: 'Sortir dengan'
          sort_asc_label: 'Urutan turun'
      pager:
        options:
          tags:
            first: '« Pertama'
            last: 'Terakhir »'
          expose:
            items_per_page_label: 'Jumlah item per halaman'
            items_per_page_options_all_label: '- Semua -'
            offset_label: Letak
      fields:
        created:
          label: Dibuat
        remote_addr:
          label: 'Alamat IP'
        view_webform_submission:
          label: Operasi-operasi
      arguments:
        in_draft:
          exception:
            title: Semua
  embed_administer:
    display_options:
      fields:
        webform_submission_bulk_form:
          action_title: Tindakan
        locked:
          label: Dikunci
        created:
          label: Dibuat
        completed:
          label: Selesai
        remote_addr:
          label: 'Alamat IP'
        operations:
          label: Operasi-operasi
      filters:
        locked:
          expose:
            label: Dikunci
  embed_manage:
    display_options:
      fields:
        webform_submission_bulk_form:
          action_title: Tindakan
        locked:
          label: Dikunci
        created:
          label: Dibuat
        completed:
          label: Selesai
        remote_addr:
          label: 'Alamat IP'
        view_webform_submission:
          label: Operasi-operasi
        edit_webform_submission:
          label: Operasi-operasi
      filters:
        locked:
          expose:
            label: Dikunci
  embed_review:
    display_options:
      fields:
        locked:
          label: Dikunci
        created:
          label: Dibuat
        completed:
          label: Selesai
        remote_addr:
          label: 'Alamat IP'
        view_webform_submission:
          label: Operasi-operasi
      filters:
        locked:
          expose:
            label: Dikunci
