asu_brand:
  asu_brand_cookie_consent_enabled: 0
  asu_brand_universal_gtm_id: GTM-KDWN8Z
  asu_brand_gtm_enabled: 0
  asu_brand_extra_gtm_id: GTM-N2JQ2V
  asu_brand_search_url: 'https://search.asu.edu/search'
  asu_brand_local_search_url: ''
_core:
  default_config_hash: QWEYAjbiw6zjBpwxKI6_hAWZsAtRWTgIxukBptvPvOU
