_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  advagg: 0
  advagg_bundler: 0
  advagg_css_minify: 0
  advagg_js_minify: 0
  advagg_mod: 0
  allowed_formats: 0
  anchor_link: 0
  asset_injector: 0
  asu_brand: 0
  asu_components_appearance: 0
  asu_degree_rfi: 0
  asu_events: 0
  asu_footer: 0
  asu_news: 0
  asu_react_core: 0
  asu_react_integration: 0
  asu_user: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  block_field: 0
  breakpoint: 0
  captcha: 0
  cas: 0
  ckeditor: 0
  ckeditor_responsive_plugin: 0
  color: 0
  comment: 0
  commerce: 0
  commerce_cart: 0
  commerce_checkout: 0
  commerce_number_pattern: 0
  commerce_order: 0
  commerce_payment: 0
  commerce_price: 0
  commerce_product: 0
  commerce_promotion: 0
  commerce_store: 0
  components: 0
  conditional_fields: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_split: 0
  config_translation: 0
  config_update: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  crop: 0
  csv_serialization: 0
  ctools: 0
  current_page_crumb: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  decorative_image_widget: 0
  domain: 0
  domain_access: 0
  domain_alias: 0
  domain_config: 0
  domain_config_ui: 0
  dropdown_language: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_browser: 0
  entity_reference_revisions: 0
  environment_indicator: 0
  environment_indicator_ui: 0
  facets: 0
  facets_searchbox_widget: 0
  fakeobjects: 0
  field: 0
  field_group: 0
  field_load_more: 0
  field_menu: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  file_replace: 0
  filter: 0
  focal_point: 0
  fontawesome: 0
  fontawesome_iconpicker_widget: 0
  group: 0
  hal: 0
  help: 0
  history: 0
  image: 0
  image_max_size_crop: 0
  image_widget_crop: 0
  imagemagick: 0
  inline_entity_form: 0
  instapage_cms_plugin: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  language: 0
  layout_builder: 0
  layout_builder_component_attributes: 0
  layout_builder_restrictions: 0
  layout_builder_st: 0
  layout_builder_styles: 0
  layout_discovery: 0
  layout_section_classes: 0
  link: 0
  linkit: 0
  locale: 0
  maxlength: 0
  media: 0
  media_directories: 0
  media_entity_file_replace: 0
  media_library: 0
  media_library_form_element: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  migrate: 0
  migrate_cron: 0
  migrate_plus: 0
  migrate_tools: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  path_redirect_import: 0
  profile: 0
  quickedit: 0
  quikpay: 0
  rabbit_hole: 0
  range: 0
  rdf: 0
  recaptcha: 0
  redirect: 0
  responsive_background_image: 0
  responsive_image: 0
  rest: 0
  rh_node: 0
  scheduled_publish: 0
  search: 0
  search_api: 0
  select2: 0
  select2_facets: 0
  serialization: 0
  shortcut: 0
  simple_sitemap: 0
  smart_trim: 0
  sophron: 0
  state_machine: 0
  system: 0
  taxonomy: 0
  tb_degrees: 0
  tb_gdmi: 0
  tb_gdmi_hubspot: 0
  tb_gdmi_reports: 0
  tb_global: 0
  tb_layouts: 0
  tb_migrations: 0
  tb_webform: 0
  text: 0
  token: 0
  toolbar: 0
  twig_tweak: 0
  tzfield: 0
  ultimate_cron: 0
  update: 0
  user: 0
  vardumper: 0
  variationcache: 0
  views_ajax_history: 0
  views_autosubmit: 0
  views_bulk_operations: 0
  views_data_export: 0
  views_filters_populate: 0
  views_load_more: 0
  views_sort_null_field: 0
  views_ui: 0
  views_year_filter: 0
  webform: 0
  webform_invitation: 0
  webform_ui: 0
  webspark_blocks: 0
  webspark_cas: 0
  webspark_ckeditor_plugins: 0
  webspark_installer_forms: 0
  webspark_module_asu_breadcrumb: 0
  webspark_module_renovation_layouts: 0
  webspark_module_views_pager: 0
  webspark_utility: 0
  webspark_webdir: 0
  workflows: 0
  extlink: 1
  noindex_metatag: 1
  pathauto: 1
  content_translation: 10
  externalauth: 10
  views: 10
  paragraphs: 11
  field_states_ui: 200
  webspark: 1000
theme:
  bartik: 0
  seven: 0
  radix: 0
  renovation: 0
  thunderbird: 0
profile: webspark
