_core:
  default_config_hash: w314Zp7B4NbrlV4KeeZLNSmTTpdJiv-KwZO2E1fSSK0
langcode: en
anonymous: Anonymous
verify_mail: 0
notify:
  cancel_confirm: false
  password_reset: false
  status_activated: false
  status_blocked: false
  status_canceled: false
  register_admin_created: false
  register_no_approval_required: false
  register_pending_approval: false
register: visitors
cancel_method: user_cancel_block
password_reset_timeout: 86400
password_strength: 0
