_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: 48f570cd-c968-4c46-871b-e979b3aa245d
name: Thunderbird
mail: Nicole.AlmondAnderson@thunderbird.asu.edu
slogan: ''
page:
  403: /node/3240
  404: ''
  front: /node/3739
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
