_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: ''
    ar: ar
    bn: bn
    my: my
    cs: cs
    nl: nl
    fr: fr
    gu: gu
    de: de
    ha: ha
    hi: hi
    hu: hu
    id: id
    it: it
    ja: ja
    jv: jv
    kk: kk
    rw-RW: rw
    ko: ko
    ms: ms
    zh-hans: zh
    pa: pa
    fa: fa
    pl: pl
    pt-br: pt
    pt-pt: pt-pt
    ro: ro
    ru: ru
    sk: sk
    es: es
    sw: sw
    sv: sv
    tl-PH: tl
    th: th
    tr: tr
    uk: uk
    ur: ur
    uz-UZ: uz
    vi: vi
    yo: yo
    zu: zu
  domains:
    en: ''
    ar: ''
    bn: ''
    my: ''
    cs: ''
    nl: ''
    fr: ''
    gu: ''
    de: ''
    ha: ''
    hi: ''
    hu: ''
    id: ''
    it: ''
    ja: ''
    jv: ''
    kk: ''
    rw-RW: ''
    ko: ''
    ms: ''
    zh-hans: ''
    pa: ''
    fa: ''
    pl: ''
    pt-br: ''
    pt-pt: ''
    ro: ''
    ru: ''
    sk: ''
    es: ''
    sw: ''
    sv: ''
    tl-PH: ''
    th: ''
    tr: ''
    uk: ''
    ur: ''
    uz-UZ: ''
    vi: ''
    yo: ''
    zu: ''
selected_langcode: site_default
