_core:
  default_config_hash: ByOVf1cU9r5NkZ4ieBJ7k9sUid6jb03ojMN1gjJ0-OU
site_key: 6LcU1QYqAAAAAK_xSAUhe5V_cuXwpz8EhcyLXJtO
secret_key: 6LcU1QYqAAAAAPJ3NQLKXOXG25ilX_CqYXUFQkXe
verify_hostname: false
use_globally: false
widget:
  theme: light
  type: image
  size: ''
  noscript: false
