psychological:
  image: '1995'
  intro_text:
    value: "<h3>Global Psychological Capital</h3>\r\n\r\n<p>High Global Psychological Capital indicates an individual’s (or group’s) passion for diversity, global exploration, diverse cultures, and alternative approaches. Individuals with high Global Psychological Capital identify as global citizens, valuing cultural exchange. A high score signifies self-confidence, a sense of humor, and risk-taking propensity. It reflects a desire for personal growth, adaptability in complex environments, and thriving amid unpredictability.</p>\r\n"
    format: full_html
  items:
    -
      image: '1999'
      title: 'Passion for Diversity'
      description:
        value: "<p>The extent you enjoy traveling to, and living in different countries, and the extent to which you enjoy exploring and getting to know people in other parts of the world.</p>\r\n\r\n<ul class=\"uds-list\">\r\n\t<li>Your enjoyment of exploring other parts of the world</li>\r\n\t<li>Your enjoyment of getting to know people from other parts of the world</li>\r\n\t<li>Your enjoyment of living in another country</li>\r\n\t<li>Your enjoyment of traveling</li>\r\n</ul>\r\n"
        format: full_html
    -
      image: '2000'
      title: 'Quest for Adventure'
      description:
        value: "<p>Your willingness to test and push your abilities, take risks, and deal with challenging and unpredictable situations.</p>\r\n\r\n<ul class=\"uds-list\">\r\n\t<li>Your interest in dealing with challenging situations</li>\r\n\t<li>Your willingness to take risk</li>\r\n\t<li>Your willingness to test your abilities</li>\r\n\t<li>Your enjoyment of dealing with unpredictable situations</li>\r\n</ul>\r\n"
        format: full_html
    -
      image: '2001'
      title: Self-Assurance
      description:
        value: "<p>Your energy and self-confidence level, and your level of comfort in uncomfortable and tough situations.</p>\r\n\r\n<ul class=\"uds-list\">\r\n\t<li>Your energy level</li>\r\n\t<li>Your self-confidence</li>\r\n\t<li>Your wittiness in tough situations</li>\r\n\t<li>Your comfort level in uncomfortable situations</li>\r\n</ul>\r\n"
        format: full_html
intellectual:
  image: '1996'
  intro_text:
    value: "<h3>Global Intellectual Capital</h3>\r\n\r\n<p>High Global Intellectual Capital scores reflect extensive industry knowledge, understanding of global competition, customer behavior, supply chains, and country risk analysis. They encompass cultural awareness, problem solving skills, and adeptness in navigating global complexities, showcasing comprehensive knowledge and critical thinking for addressing multifaceted global business challenges.</p>\r\n"
    format: full_html
  items:
    -
      image: '2004'
      title: 'Global Business Savvy'
      description:
        value: "<p>Your knowledge of global industry, global strategies, international business, and global supplier options.</p>\r\n\r\n<ul class=\"uds-list\">\r\n\t<li>Your knowledge of global industry</li>\r\n\t<li>Your knowledge of global competitive business and marketing strategies</li>\r\n\t<li>Your knowledge of how to transact business and assess risks of doing business internationally</li>\r\n\t<li>Your knowledge of supplier options in other parts of the world</li>\r\n</ul>\r\n"
        format: full_html
    -
      image: '2003'
      title: 'Cosmopolitan Outlook'
      description:
        value: "<p>Your up-to-date knowledge of cultures, economic and political issues, and histories of diverse countries.</p>\r\n\r\n<ul class=\"uds-list\">\r\n\t<li>Your knowledge of cultures in different parts of the world</li>\r\n\t<li>Your knowledge of geography, history, and important persons of several countries</li>\r\n\t<li>Your knowledge of economic and political issues, concerns, hot topics, etc. of major regions of the world</li>\r\n\t<li>Your up-to-date knowledge of important world events</li>\r\n</ul>\r\n"
        format: full_html
    -
      image: '2002'
      title: 'Cognitive Complexity'
      description:
        value: "<p>Your ability and ease of understanding, navigating, and communicating complex concepts and problems.</p>\r\n\r\n<ul class=\"uds-list\">\r\n\t<li>Your ability to grasp complex concepts quickly</li>\r\n\t<li>The strength of your analytical and problem-solving skills</li>\r\n\t<li>Your ability to understand abstract ideas</li>\r\n\t<li>Your ability to take complex issues and explain the main points simply and understandably</li>\r\n</ul>\r\n"
        format: full_html
social:
  image: '1997'
  intro_text:
    value: "<h3>Global Social Capital</h3>\r\n\r\n<p>High Global Social Capital&nbsp;scores reflect excellence in cultivating trust with diverse individuals, effective leadership across cultures, and diplomacy. Individuals with high scores on Global Social Capital possess active listening skills, facilitate inclusive conversations, and foster consensus among disparate viewpoints. A high score indicates empathy and emotional connections with people globally, alongside the ability to engage and maintain a broad network of friends and colleagues across countries.</p>\r\n"
    format: full_html
  items:
    -
      image: '1999'
      title: 'Intercultural Empathy'
      description:
        value: "<p>Your ability to communicate and work well, and emotionally connect with people from other parts of the world.</p>\r\n\r\n<ul class=\"uds-list\">\r\n\t<li>Your ability to work well with people from other parts of the world</li>\r\n\t<li>Your ability to understand nonverbal expressions of people from other cultures</li>\r\n\t<li>Your ability to emotionally connect to people from other cultures</li>\r\n\t<li>Your ability to engage people from other parts of the world to work together</li>\r\n</ul>\r\n"
        format: full_html
    -
      image: '2005'
      title: 'Interpersonal Impact'
      description:
        value: "<p>Your experience in negotiating with people in other cultures, and your ability to build personal and professional networks with people in other countries.</p>\r\n\r\n<ul class=\"uds-list\">\r\n\t<li>Your experience in negotiating contracts/agreements in other cultures</li>\r\n\t<li>Your strong networks with people from other cultures and with influential people</li>\r\n\t<li>Your reputation as a leader</li>\r\n</ul>\r\n"
        format: full_html
    -
      image: '2006'
      title: Diplomacy
      description:
        value: "<p>Your ability to be a good listener, to collaborate, and to create agreement among diverse and divergent views.</p>\r\n\r\n<ul class=\"uds-list\">\r\n\t<li>Your ease of starting a conversation with a stranger</li>\r\n\t<li>Your ability to integrate diverse perspectives</li>\r\n\t<li>Your ability to listen to what others have to say</li>\r\n\t<li>Your willingness to collaborate</li>\r\n</ul>\r\n"
        format: full_html
digital:
  image: '1998'
  intro_text:
    value: "<h3>Global Digital Capital</h3>\r\n\r\n<p>Organizations all over the world are making huge investments in advanced digital technologies to transform their operations, client experiences, or their business models. Successful digital transformation requires leaders who have high levels of global digital capital, which reflects openness to radical, creative, and rapid change, sufficient knowledge of advanced technologies and their opportunities and challenges, the ability to communicate a clear transformative vision and build trust, and the ability to build employee buy in.</p>\r\n"
    format: full_html
  items:
    -
      image: '2007'
      title: 'Digital Advocacy'
      description:
        value: "<p>Your knowledge of the opportunities and challenges created by digital transformation, and your ability to communicate an effective vision of digital transformation.</p>\r\n\r\n<ul class=\"uds-list\">\r\n\t<li>Your&nbsp;knowledge of the opportunities created by digital transformation</li>\r\n\t<li>Your knowledge of the impact of digital transformation on client experience</li>\r\n\t<li>Your knowledge of the impact of digital transformation on internal operations</li>\r\n\t<li>Your knowledge of the impact of digital transformation on business model</li>\r\n\t<li>Your knowledge of the impact of digital transformation on jobs in the organization</li>\r\n\t<li>Your knowledge of the basics of advanced technologies</li>\r\n\t<li>Your knowledge of how to communicate a vision of digital transformation</li>\r\n</ul>\r\n"
        format: full_html
    -
      image: '2007'
      title: 'Digital Implementation'
      description:
        value: "<p>Your knowledge of the roles played by different groups in digital transformation and your ability to mobilize the workforce to embrace digital transformation.</p>\r\n\r\n<ul class=\"uds-list\">\r\n\t<li>Your knowledge of how to manage digital transformation</li>\r\n\t<li>Your knowledge of the role of Information Technology group in digital transformation</li>\r\n\t<li>Your knowledge of the role of middle management in digital transformation</li>\r\n\t<li>Your knowledge of the potential sources of resistance to digital transformation</li>\r\n\t<li>Your knowledge of how to build employee confidence in digital transformation</li>\r\n</ul>\r\n"
        format: full_html
    -
      image: '2007'
      title: 'Growth Mindset'
      description:
        value: "<p>Your belief in employees’ learning capacity and your ability to support employees’ continuous learning and creating a high trust environment.</p>\r\n\r\n<ul class=\"uds-list\">\r\n\t<li>Your ability to build trust</li>\r\n\t<li>Your ability to encourage continuous learning</li>\r\n\t<li>Your ability to encourage constructive debate</li>\r\n\t<li>Your ability to empower employees</li>\r\n</ul>\r\n"
        format: full_html
