features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
  path: 'public://favicon-white.png'
favicon:
  use_default: 0
  path: 'public://favicon-white.png'
  mimetype: image/png
default_faculty_bio_image: {  }
faculty_default_img: '378'
