display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: 'दोबारा से स्थापित करें|'
          exposed_sorts_label: 'क्रमबद्ध द्वारा'
          sort_desc_label: अवरोही
      pager:
        options:
          expose:
            items_per_page_label: 'विषय प्रति पृष्ठ'
            items_per_page_options_all_label: '-सभी-'
      fields:
        placed:
          label: तारीख
        type:
          label: प्रकार
        operations:
          label: कार्यवाही
      filters:
        type:
          expose:
            label: प्रकार
  page_1:
    display_title: पृष्ठ
