display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: 'लागू करें'
          reset_button_label: 'दोबारा से स्थापित करें|'
          exposed_sorts_label: 'क्रमबद्ध द्वारा'
          sort_desc_label: अवरोही
      pager:
        options:
          expose:
            items_per_page_label: 'विषय प्रति पृष्ठ'
            items_per_page_options_all_label: '-सभी-'
      fields:
        nothing:
          alter:
            text: 'संपादित करें'
        nothing_1:
          alter:
            text: मिटायें
        title:
          label: शीर्षक
        dropbutton:
          label: कार्यवाही
      filters:
        title:
          expose:
            label: शीर्षक
