display:
  default:
    display_title: डीफॉल्ट
    display_options:
      fields:
        operations:
          label: कार्यवाही
      exposed_form:
        options:
          submit_button: 'लागू करें'
          reset_button_label: 'दोबारा से स्थापित करें|'
          exposed_sorts_label: 'क्रमबद्ध द्वारा'
          sort_desc_label: अवरोही
      arguments:
        order_id:
          exception:
            title: सभी
  page_1:
    display_title: पृष्ठ
