display:
  default:
    display_title: डीफॉल्ट
    display_options:
      fields:
        comment_bulk_form:
          action_title: कार्रवाई
        name:
          label: लेखक
        changed:
          label: अद्यतित
        operations:
          label: कार्यवाही
      pager:
        options:
          expose:
            items_per_page_label: 'विषय प्रति पृष्ठ'
            items_per_page_options_all_label: '-सभी-'
      exposed_form:
        options:
          reset_button_label: 'दोबारा से स्थापित करें|'
          exposed_sorts_label: 'क्रमबद्ध द्वारा'
          sort_desc_label: अवरोही
      filters:
        langcode:
          expose:
            label: भाषा
  page_unapproved:
    display_options:
      fields:
        comment_bulk_form:
          action_title: कार्रवाई
        name:
          label: लेखक
        changed:
          label: अद्यतित
        operations:
          label: कार्यवाही
      filters:
        langcode:
          expose:
            label: भाषा
