display:
  default:
    display_title: डीफॉल्ट
    display_options:
      exposed_form:
        options:
          submit_button: 'लागू करें'
          reset_button_label: 'दोबारा से स्थापित करें|'
          exposed_sorts_label: 'क्रमबद्ध द्वारा'
          sort_desc_label: अवरोही
      pager:
        options:
          expose:
            items_per_page_label: 'विषय प्रति पृष्ठ'
            items_per_page_options_all_label: '-सभी-'
      fields:
        name:
          label: नाम
        operations:
          label: कार्यवाही
      filters:
        name:
          expose:
            label: नाम
        status:
          expose:
            label: अवस्था
  admin:
    display_title: पृष्ठ
    display_options:
      menu:
        title: सूची
      tab_options:
        title: सूची
