content:
  field_body:
    third_party_settings:
      maxlength:
        maxlength_js_label: 'Conteúdo limitado a @limit caracteres, restam: <strong>@remaining</strong>'
  field_cta:
    settings:
      title_plural: Parágrafos
  field_cta_secondary:
    settings:
      title_plural: Parágrafos
