content:
  field_anchor_menu_settings:
    settings:
      title: Parágrafo
      title_plural: Parágrafos
  field_paragraph:
    settings:
      title: Parágrafo
      title_plural: Parágrafos
  field_tooltip:
    settings:
      title: Parágrafo
      title_plural: Parágrafos
