third_party_settings:
  field_group:
    group_display_settings:
      label: 'Opções de exibição'
content:
  field_filter_title:
    third_party_settings:
      maxlength:
        maxlength_js_label: 'Conteúdo limitado a @limit caracteres, restam: <strong>@remaining</strong>'
  field_people_search:
    third_party_settings:
      maxlength:
        maxlength_js_label: 'Conteúdo limitado a @limit caracteres, restam: <strong>@remaining</strong>'
