content:
  field_anchor_menu_settings:
    settings:
      title: Par치grafo
      title_plural: Par치grafos
  field_testimonial_component:
    settings:
      title: Par치grafo
      title_plural: Par치grafos
