display:
  default:
    display_title: Principal
    display_options:
      exposed_form:
        options:
          submit_button: Filtrar
          reset_button_label: Redefinir
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Ascendente
          sort_desc_label: Decrescente
      pager:
        options:
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
          tags:
            previous: '‹ anterior'
            next: 'próximo ›'
            first: '« primeiro'
            last: 'último »'
      fields:
        commerce_order_bulk_form:
          action_title: 'Selecione a ação'
        type:
          label: Tipo
          separator: ', '
        store_id:
          label: Loja
          separator: ', '
        uid:
          label: Cliente
          separator: ', '
        mail:
          label: Email
          separator: ', '
        total_price__number:
          label: Total
          separator: ', '
        changed:
          label: Atualizado
          separator: ', '
        operations:
          label: Operações
      filters:
        type:
          expose:
            label: Tipo
  page_1:
    display_title: Página
