label: Lojas
display:
  default:
    display_title: Principal
    display_options:
      title: Lojas
      fields:
        commerce_store_bulk_form:
          action_title: 'Selecione a ação'
        is_default:
          label: Padrão
          separator: ', '
        name:
          label: Nome
          separator: ', '
        changed:
          label: Atualizado
          separator: ', '
        type:
          label: Tipo
          separator: ', '
        operations:
          label: Operações
      pager:
        options:
          tags:
            next: 'próximo ›'
            previous: '‹ anterior'
            first: '« primeiro'
            last: 'último »'
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Redefinir
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Ascendente
          sort_desc_label: Decrescente
      filters:
        type:
          expose:
            label: Tipo
  page_1:
    display_title: Página
