display:
  default:
    display_title: Principal
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Redefinir
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Ascendente
          sort_desc_label: Decrescente
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« Primeiro'
            last: 'Último »'
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
      fields:
        nid:
          separator: ', '
        delta:
          format_plural_string: !!binary MQNAY291bnQ=
        nothing:
          alter:
            text: Editar
        nothing_1:
          alter:
            text: Apagar
        title:
          label: Título
          separator: ', '
        sp_dynamic:
          separator: ', '
        sp_dynamic_1:
          separator: ', '
        dropbutton:
          label: Operações
      filters:
        title:
          expose:
            label: Título
  block_1:
    display_title: Bloco
