label: Promoções
display:
  default:
    display_title: Padrão
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Redefinir
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Ascendente
          sort_desc_label: Decrescente
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« Primeiro'
            last: 'Último »'
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
      fields:
        name:
          label: Nome
          separator: ', '
        offer__target_plugin_id:
          label: 'Tipo de oferta'
          separator: ', '
        usage_limit:
          label: Uso
          separator: ', '
        usage_limit_customer:
          separator: ', '
        start_date:
          label: 'Data inicial'
          separator: ', '
        end_date:
          label: 'Data final'
          separator: ', '
        operations:
          label: Operações
      filters:
        name:
          expose:
            label: Nome
        offer__target_plugin_id:
          expose:
            label: 'Tipo de oferta'
        code:
          expose:
            label: 'Código do cupom'
        status:
          expose:
            label: Status
      title: Promoções
  admin:
    display_title: Página
    display_options:
      menu:
        title: Lista
      tab_options:
        title: Lista
