label: 'Membros do grupo'
display:
  default:
    display_title: Principal
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Redefinir
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Ascendente
          sort_desc_label: Decrescente
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« Primeiro'
            last: 'Último »'
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
      fields:
        name:
          label: Usuário
          separator: ', '
        group_roles:
          label: Papéis
          separator: ', '
        changed:
          label: Atualizado
          separator: ', '
        created:
          label: Inscrito
          separator: ', '
        edit_group_content:
          text: 'Editar membro'
        delete_group_content:
          text: 'Remover membro'
        dropbutton:
          label: Operações
      empty:
        area_text_custom:
          content: 'Nenhum membro inscrito'
      arguments:
        gid:
          exception:
            title: Tudo
          title: '{{ arguments.gid|placeholder }} membros'
      title: Membros
  page_1:
    display_title: Página
    display_options:
      menu:
        title: Membros
