content:
  field_anchor_menu_settings:
    settings:
      title_plural: パラグラフ
  field_testimonial_component:
    settings:
      title_plural: パラグラフ
  field_tooltip:
    settings:
      title_plural: パラグラフ
