content:
  field_anchor_menu_settings:
    settings:
      title_plural: パラグラフ
  field_card_group:
    settings:
      title_plural: パラグラフ
  field_cta:
    settings:
      title_plural: パラグラフ
  field_tooltip:
    settings:
      title_plural: パラグラフ
