label: ストア
display:
  default:
    display_title: マスター
    display_options:
      title: ストア
      fields:
        commerce_store_bulk_form:
          action_title: 選択リスト付
        is_default:
          label: デフォルト
          separator: ', '
        name:
          label: 名前
          separator: ', '
        changed:
          label: 更新
          separator: ', '
        type:
          label: タイプ
          separator: ', '
        operations:
          label: 操作
      pager:
        options:
          tags:
            next: '次へ ›'
            previous: '‹ 前へ'
            first: '« 最初へ'
            last: '最後 »'
          expose:
            items_per_page_label: ページ毎の件数
            items_per_page_options_all_label: '- 全て -'
            offset_label: オフセット
      exposed_form:
        options:
          submit_button: 適用
          reset_button_label: リセット
          exposed_sorts_label: 並び替え基準
          sort_asc_label: 昇順
          sort_desc_label: 降順
      filters:
        type:
          expose:
            label: タイプ
  page_1:
    display_title: ページ
