display:
  default:
    display_title: ਮੂਲ
    display_options:
      exposed_form:
        options:
          reset_button_label: ਰੀ-ਸੈੱਟ
      fields:
        name:
          label: ਨਾਂ
      filters:
        name:
          expose:
            label: ਨਾਂ
        status:
          expose:
            label: ਹਾਲਤ
  admin:
    display_title: ਸਫਾ
    display_options:
      menu:
        title: ਸੂਚੀ
      tab_options:
        title: ਸੂਚੀ
