display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: ਰੀ-ਸੈੱਟ
      fields:
        name:
          label: ਯੂਜ਼ਰ
        group_roles:
          label: ਰੋਲ
      arguments:
        gid:
          exception:
            title: ਸਭ
  page_1:
    display_title: ਸਫਾ
