display:
  default:
    display_title: ਮੂਲ
    display_options:
      fields:
        title:
          label: ਟਾਈਟਲ
        name:
          label: ਲੇਖਕ
      exposed_form:
        options:
          submit_button: ਫਿਲਟਰ
          reset_button_label: ਰੀ-ਸੈੱਟ
      filters:
        title:
          expose:
            label: ਟਾਈਟਲ
        langcode:
          expose:
            label: ਭਾਸ਼ਾ
