display:
  default:
    display_title: Principal
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
      fields:
        remove_button:
          label: Remover
      arguments:
        order_id:
          exception:
            title: Todos
