display:
  default:
    display_title: 'Por defeito'
    display_options:
      fields:
        comment_bulk_form:
          action_title: Ação
        name:
          label: Autor
        changed:
          label: Atualizado
        operations:
          label: Operações
      pager:
        options:
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
      exposed_form:
        options:
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
      filters:
        langcode:
          expose:
            label: Idioma
  page_unapproved:
    display_options:
      fields:
        comment_bulk_form:
          action_title: Ação
        name:
          label: Autor
        changed:
          label: Atualizado
        operations:
          label: Operações
      filters:
        langcode:
          expose:
            label: Idioma
