display:
  default:
    display_title: 'Por defeito'
    display_options:
      fields:
        media_bulk_form:
          action_title: Ação
      pager:
        options:
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
      exposed_form:
        options:
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
      filters:
        status:
          group_info:
            label: Publicado
            group_items:
              1:
                title: Publicado
              2:
                title: 'Não publicado'
        name:
          expose:
            label: Nome
        langcode:
          expose:
            label: Idioma
  page:
    display_title: Página
    display_options:
      fields:
        media_bulk_form:
          action_title: Ação
        edit_media:
          text: Editar
        delete_media:
          text: Eliminar
  widget:
    display_options:
      arguments:
        bundle:
          exception:
            title: Todos
      filters:
        name:
          expose:
            label: Nome
  widget_table:
    display_options:
      fields:
        name:
          label: Nome
        uid:
          label: Autor
        changed:
          label: Atualizado
      arguments:
        bundle:
          exception:
            title: Todos
      filters:
        name:
          expose:
            label: Nome
