display:
  default:
    display_title: 'Por defeito'
    display_options:
      fields:
        user_bulk_form:
          label: 'Atualização em massa'
        name:
          label: 'Nome de utilizador'
        status:
          label: Estado
          settings:
            format_custom_true: Ativo
        roles_target_id:
          label: 'Grupos de utilizador'
        operations:
          label: Operações
      pager:
        options:
          tags:
            first: '« Primeira'
            last: 'Última »'
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
      exposed_form:
        options:
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
      filters:
        status:
          group_info:
            label: Estado
            group_items:
              1:
                title: Ativo
        roles_target_id:
          expose:
            label: Grupo
        permission:
          expose:
            label: Permissão
  page_1:
    display_title: Página
    display_options:
      menu:
        title: Lista
