display:
  default:
    display_title: 'Por defeito'
    display_options:
      fields:
        title:
          label: Título
        type:
          label: 'Tipo de conteúdo'
        name:
          label: Autor
        changed:
          label: Atualizado
        operations:
          label: Operações
      pager:
        options:
          tags:
            first: '« Primeira'
            last: 'Última »'
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
      exposed_form:
        options:
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
      filters:
        title:
          expose:
            label: Título
        type:
          expose:
            label: 'Tipo de conteúdo'
        langcode:
          expose:
            label: Idioma
