display:
  default:
    display_title: 'Por defeito'
    display_options:
      fields:
        filename:
          label: Nome
        filesize:
          label: Tamanho
        status:
          label: Estado
      pager:
        options:
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
      exposed_form:
        options:
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
      filters:
        filename:
          expose:
            label: 'Nome do ficheiro'
        status:
          expose:
            label: Estado
  page_2:
    display_options:
      fields:
        entity_label:
          label: Entidade
        type:
          label: 'Tipo de entidade'
      pager:
        options:
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
      arguments:
        fid:
          exception:
            title: Todos
