display:
  default:
    display_title: 'Por defeito'
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
      empty:
        area_text_custom:
          content: 'Conteúdo não disponível'
