label: Redirecionamento
display:
  default:
    display_title: Principal
    display_options:
      exposed_form:
        options:
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
      pager:
        options:
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
      fields:
        created:
          label: Criado
      title: Redirecionamento
  page_1:
    display_title: Página
