display:
  default:
    display_title: 'Por defeito'
    display_options:
      fields:
        media_bulk_form:
          action_title: Ação
        bundle:
          label: Tipo
        uid:
          label: Autor
        status:
          label: Estado
          settings:
            format_custom_false: 'Não publicado'
            format_custom_true: Publicado
        changed:
          label: Atualizado
        operations:
          label: Operações
      pager:
        options:
          tags:
            first: '« Primeira'
            last: 'Última »'
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
      exposed_form:
        options:
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
      filters:
        bundle:
          expose:
            label: Tipo
        status:
          group_info:
            label: 'Estado da publicação'
            group_items:
              1:
                title: Publicado
              2:
                title: 'Não publicado'
        langcode:
          expose:
            label: Idioma
