label: 'Membros do grupo'
display:
  default:
    display_title: Principal
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
      pager:
        options:
          tags:
            first: '« Primeira'
            last: 'Última »'
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
      fields:
        name:
          label: Utilizador
        group_roles:
          label: 'Grupos de utilizador'
        changed:
          label: Atualizado
        created:
          label: 'Membro desde'
        edit_group_content:
          text: 'Editar membro'
        delete_group_content:
          text: 'Remover membro'
        dropbutton:
          label: Operações
      empty:
        area_text_custom:
          content: 'Nenhum membro disponível.'
      arguments:
        gid:
          exception:
            title: Todos
          title: '{{ arguments.gid|placeholder }} membros'
      title: Membros
  page_1:
    display_title: Página
    display_options:
      menu:
        title: Membros
