label: Conteúdo
display:
  default:
    display_title: 'Por defeito'
    display_options:
      title: Conteúdo
      fields:
        title:
          label: Título
        type:
          label: 'Tipo de conteúdo'
        name:
          label: Autor
        status:
          label: Estado
          settings:
            format_custom_false: 'Não publicado'
            format_custom_true: Publicado
        changed:
          label: Atualizado
        operations:
          label: Operações
      pager:
        options:
          tags:
            first: '« Primeira'
            last: 'Última »'
      exposed_form:
        options:
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
      empty:
        area_text_custom:
          content: 'Conteúdo não disponível'
      filters:
        title:
          expose:
            label: Título
        type:
          expose:
            label: 'Tipo de conteúdo'
        status:
          expose:
            label: Estado
          group_info:
            label: 'Estado da publicação'
            group_items:
              1:
                title: Publicado
              2:
                title: 'Não publicado'
        langcode:
          expose:
            label: Idioma
  page_1:
    display_title: Página
    display_options:
      menu:
        title: Conteúdo
      tab_options:
        title: Conteúdo
