display:
  default:
    display_title: 'Por defeito'
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
      pager:
        options:
          tags:
            first: '« Primeira'
            last: 'Última »'
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
      fields:
        name:
          label: Nome
        operations:
          label: Operações
      filters:
        name:
          expose:
            label: Nome
        status:
          expose:
            label: Estado
  admin:
    display_title: Página
    display_options:
      menu:
        title: Lista
      tab_options:
        title: Lista
