display:
  default:
    display_title: Principal
    display_options:
      fields:
        is_default:
          label: 'Por defeito'
        name:
          label: Nome
        changed:
          label: Atualizado
        type:
          label: Tipo
        operations:
          label: Operações
      pager:
        options:
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
      filters:
        type:
          expose:
            label: Tipo
  page_1:
    display_title: Página
