display:
  default:
    display_title: 'Por defecto'
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      pager:
        options:
          tags:
            first: '« Primero'
            last: 'Último »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      fields:
        name:
          label: Nombre
        operations:
          label: Operaciones
      filters:
        name:
          expose:
            label: Nombre
        status:
          expose:
            label: Estado
  admin:
    display_title: Página
    display_options:
      menu:
        title: Listado
      tab_options:
        title: Listado
