display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      pager:
        options:
          tags:
            first: '« Primero'
            last: 'Último »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      fields:
        code:
          label: Código
        operations:
          label: Operaciones
      filters:
        code:
          expose:
            label: Código
      arguments:
        promotion_id:
          exception:
            title: Todo(s)
  page_1:
    display_title: Página
