label: Multimedia
display:
  default:
    display_title: 'Por defecto'
    display_options:
      title: Multimedia
      fields:
        media_bulk_form:
          action_title: Acción
        bundle:
          label: Tipo
        uid:
          label: Autor
        status:
          label: Estado
          settings:
            format_custom_false: 'Sin publicar'
            format_custom_true: Publicado
        changed:
          label: Actualizado
        operations:
          label: Operaciones
      pager:
        options:
          tags:
            first: '« Primero'
            last: 'Último »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      exposed_form:
        options:
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      filters:
        bundle:
          expose:
            label: Tipo
        status:
          group_info:
            label: 'Estado de publicación'
            group_items:
              1:
                title: Publicado
              2:
                title: 'Sin publicar'
        langcode:
          expose:
            label: Idioma
  media_page_list:
    display_title: Multimedia
    display_options:
      menu:
        title: Multimedia
