display:
  default:
    display_title: 'Por defecto'
    display_options:
      fields:
        completed:
          label: Completado
        operations:
          label: Operaciones
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      arguments:
        order_id:
          exception:
            title: Todo(s)
  page_1:
    display_title: PÃ¡gina
