label: 'Miembros del grupo'
display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      pager:
        options:
          tags:
            first: '« Primero'
            last: 'Último »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      fields:
        name:
          label: Usuario
        group_roles:
          label: Roles
        changed:
          label: Actualizado
        created:
          label: 'se unió'
        edit_group_content:
          text: 'Editar miembro'
        delete_group_content:
          text: 'Eliminar el miembro'
        dropbutton:
          label: Operaciones
      arguments:
        gid:
          exception:
            title: Todo(s)
      title: Miembros
  page_1:
    display_title: Página
    display_options:
      menu:
        title: Miembros
