display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      fields:
        placed:
          label: Fecha
        type:
          label: Tipo
        operations:
          label: Operaciones
      filters:
        type:
          expose:
            label: Tipo
  page_1:
    display_title: Página
