display:
  default:
    display_title: 'Por defecto'
    display_options:
      fields:
        filename:
          label: Nombre
        filesize:
          label: Tamaño
        status:
          label: Estado
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      exposed_form:
        options:
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      filters:
        filename:
          expose:
            label: 'Nombre de archivo'
        status:
          expose:
            label: Estado
  page_2:
    display_options:
      fields:
        entity_label:
          label: Entidad
        type:
          label: 'Tipo de entidad'
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      arguments:
        fid:
          exception:
            title: Todo(s)
