display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      fields:
        title:
          label: Título
      arguments:
        order_item_id:
          exception:
            title: Todo(s)
