display:
  default:
    display_title: Máster
    display_options:
      fields:
        is_default:
          label: 'Por defecto'
        name:
          label: Nombre
        changed:
          label: Actualizado
        type:
          label: Tipo
        operations:
          label: Operaciones
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      filters:
        type:
          expose:
            label: Tipo
  page_1:
    display_title: Página
