label: '최근 댓글 목록'
display:
  default:
    display_title: 기본값
    display_options:
      title: '최근 댓글 목록'
  block_1:
    display_title: 블록
    display_options:
      block_description: '최근 댓글 목록'
      block_category: 목록(보기)
