display:
  default:
    display_title: 기본값
    display_options:
      exposed_form:
        options:
          submit_button: 적용
          reset_button_label: 재설정
          exposed_sorts_label: 정렬기준
          sort_asc_label: Asc
          sort_desc_label: 설명
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« 처음'
            last: '마지막 »'
          expose:
            items_per_page_label: '페이지 당 항목 수'
            items_per_page_options_all_label: '- 모두 -'
            offset_label: 건너뛰기
      fields:
        name:
          label: 이름
        usage_limit:
          label: '사용 내역'
        start_date:
          label: 시작일
        end_date:
          label: 마감일
        operations:
          label: 작업
      filters:
        name:
          expose:
            label: 이름
        status:
          expose:
            label: 상태
  admin:
    display_title: 쪽
    display_options:
      menu:
        title: 목록
      tab_options:
        title: 목록
