label: 주문
display:
  default:
    display_title: 마스터
    display_options:
      exposed_form:
        options:
          submit_button: 필터
          reset_button_label: 재설정
          exposed_sorts_label: 정렬기준
          sort_asc_label: Asc
          sort_desc_label: 설명
      pager:
        options:
          expose:
            items_per_page_label: '페이지 당 항목 수'
            items_per_page_options_all_label: '- 모두 -'
            offset_label: 건너뛰기
          tags:
            previous: '‹ 이전'
            next: '다음 ›'
            first: '« 처음 페이지'
            last: '마지막 페이지 »'
      fields:
        order_number:
          label: '#'
        placed:
          label: 날짜
        type:
          label: 종류
        store_id:
          label: 상점
        uid:
          label: 고객
        mail:
          label: 이메일
        state:
          label: 상태
        total_price__number:
          label: 총계
        operations:
          label: 작업
      filters:
        order_number:
          expose:
            label: 주문번호
        type:
          expose:
            label: 종류
        state:
          expose:
            label: 상태
      title: 주문
  page_1:
    display_title: 쪽
    display_options:
      menu:
        title: 주문
      tab_options:
        title: 주문
