display:
  default:
    display_title: 마스터
    display_options:
      exposed_form:
        options:
          submit_button: 적용
          reset_button_label: 재설정
          exposed_sorts_label: 정렬기준
          sort_asc_label: Asc
          sort_desc_label: 설명
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« 처음'
            last: '마지막 »'
          expose:
            items_per_page_label: '페이지 당 항목 수'
            items_per_page_options_all_label: '- 모두 -'
            offset_label: 건너뛰기
      fields:
        nothing:
          alter:
            text: 편집하기
        nothing_1:
          alter:
            text: 삭제하기
        title:
          label: 제목
        dropbutton:
          label: 작업
      filters:
        title:
          expose:
            label: 제목
  block_1:
    display_title: 블록
