display:
  default:
    display_title: 마스터
    display_options:
      exposed_form:
        options:
          submit_button: 필터
          reset_button_label: 재설정
          exposed_sorts_label: 정렬기준
          sort_asc_label: Asc
          sort_desc_label: 설명
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« 처음'
            last: '마지막 »'
          expose:
            items_per_page_label: '페이지 당 항목 수'
            items_per_page_options_all_label: '- 모두 -'
            offset_label: 건너뛰기
      fields:
        code:
          label: '언어 코드'
        usage_limit:
          label: '사용 내역'
        operations:
          label: 작업
      filters:
        code:
          expose:
            label: '언어 코드'
      arguments:
        promotion_id:
          exception:
            title: 전체
  page_1:
    display_title: 쪽
