display:
  default:
    display_title: 마스터
    display_options:
      exposed_form:
        options:
          submit_button: 적용
          reset_button_label: 재설정
          exposed_sorts_label: 정렬기준
          sort_asc_label: Asc
          sort_desc_label: 설명
      fields:
        title:
          label: 제목
        unit_price__number:
          label: 단가
        quantity:
          label: 수량
      arguments:
        order_item_id:
          exception:
            title: 전체
