display:
  default:
    display_title: 마스터
    display_options:
      exposed_form:
        options:
          submit_button: 적용
          reset_button_label: 재설정
          exposed_sorts_label: 정렬기준
          sort_asc_label: Asc
          sort_desc_label: 설명
      fields:
        purchased_entity:
          label: 항목
        unit_price__number:
          label: 가격
        remove_button:
          label: 제거
        total_price__number:
          label: 총계
      arguments:
        order_id:
          exception:
            title: 전체
