display:
  default:
    display_title: 기본값
    display_options:
      fields:
        title:
          label: 제목
        type:
          label: '콘텐츠 유형'
        name:
          label: 작성자
        moderation_state:
          label: '검토 상태'
        changed:
          label: 갱신됨
        operations:
          label: 작업
      pager:
        options:
          tags:
            next: '다음 ›'
            previous: '‹ 이전'
            first: '« 처음'
            last: '마지막 »'
          expose:
            items_per_page_label: '페이지 당 항목 수'
            items_per_page_options_all_label: '- 모두 -'
            offset_label: 건너뛰기
      exposed_form:
        options:
          submit_button: 필터
          reset_button_label: 재설정
          exposed_sorts_label: 정렬기준
          sort_asc_label: Asc
          sort_desc_label: 설명
      filters:
        title:
          expose:
            label: 제목
        type:
          expose:
            label: '콘텐츠 유형'
        moderation_state:
          expose:
            label: '검토 상태'
        langcode:
          expose:
            label: 언어
