display:
  default:
    display_title: 마스터
    display_options:
      exposed_form:
        options:
          submit_button: 적용
          reset_button_label: 재설정
          exposed_sorts_label: 정렬기준
          sort_asc_label: Asc
          sort_desc_label: 설명
      pager:
        options:
          tags:
            previous: '‹ 이전'
            next: '다음 ›'
            first: '« 처음'
            last: '마지막 »'
          expose:
            items_per_page_label: '페이지 당 항목 수'
            items_per_page_options_all_label: '- 모두 -'
            offset_label: 건너뛰기
      fields:
        order_id:
          label: 아이디
        order_number:
          label: 주문번호
        placed:
          label: 날짜
        total_price__number:
          label: 총계
        state:
          label: 상태
      title: 주문
      arguments:
        uid:
          exception:
            title: 전체
  order_page:
    display_options:
      menu:
        title: 주문
