content:
  field_anchor_menu_settings:
    settings:
      title: Paragraf
      title_plural: Paragrafer
  field_card_group:
    settings:
      title: Paragraf
      title_plural: Paragrafer
  field_cta:
    settings:
      title: Paragraf
      title_plural: Paragrafer
  field_tooltip:
    settings:
      title: Paragraf
      title_plural: Paragrafer
