content:
  field_anchor_menu_settings:
    settings:
      title: Paragraf
      title_plural: Paragrafer
  field_testimonial_component:
    settings:
      title: Paragraf
      title_plural: Paragrafer
