display:
  default:
    display_title: Huvud
    display_options:
      exposed_form:
        options:
          submit_button: Filtrera
          reset_button_label: Återställ
          exposed_sorts_label: 'Sortera efter'
          sort_asc_label: Stigande
          sort_desc_label: Fallande
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« Första'
            last: 'Sista »'
          expose:
            items_per_page_label: 'Inlägg per sida'
            items_per_page_options_all_label: '- Alla -'
            offset_label: Kompensera
      fields:
        code:
          label: Kod
          separator: ', '
        usage_limit:
          label: Användning
          separator: ', '
        usage_limit_customer:
          separator: ', '
        operations:
          label: Funktioner
      filters:
        code:
          expose:
            label: Kod
      arguments:
        promotion_id:
          exception:
            title: Alla
  page_1:
    display_title: Sida
