display:
  default:
    display_title: Gawan
    display_options:
      exposed_form:
        options:
          reset_button_label: Baléknā
          sort_asc_label: 'Urut Maju'
          sort_desc_label: 'Urut Mundur'
      empty:
        area_text_custom:
          content: 'Ora ānā kontèn sing cumawis.'
