display:
  default:
    display_title: Gawan
    display_options:
      fields:
        type:
          label: Tipe
        timestamp:
          label: Tanggal
        message:
          label: Pesen
        name:
          label: Panganggo
        link:
          label: Operasi
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- Kabeh -'
      exposed_form:
        options:
          reset_button_label: Baléknā
          sort_asc_label: 'Urut Maju'
          sort_desc_label: 'Urut Mundur'
      filters:
        type:
          expose:
            label: Tipe
  page:
    display_title: Kācā
