display:
  default:
    display_title: Gawan
    display_options:
      fields:
        title:
          label: Judul
        type:
          label: 'Tipe kontèn'
        name:
          label: Penulis
        changed:
          label: 'Wis anyar'
        operations:
          label: Operasi
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- Kabeh -'
      exposed_form:
        options:
          reset_button_label: Baléknā
          sort_asc_label: 'Urut Maju'
          sort_desc_label: 'Urut Mundur'
      filters:
        title:
          expose:
            label: Judul
        type:
          expose:
            label: 'Tipe kontèn'
        langcode:
          expose:
            label: Basa
