display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Baléknā
          sort_asc_label: 'Urut Maju'
          sort_desc_label: 'Urut Mundur'
      arguments:
        order_id:
          exception:
            title: Kabèh
