display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Baléknā
          sort_asc_label: 'Urut Maju'
          sort_desc_label: 'Urut Mundur'
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- Kabeh -'
      fields:
        name:
          label: Panganggo
        group_roles:
          label: Parāgā
        changed:
          label: 'Wis anyar'
        created:
          label: Nggabung
        dropbutton:
          label: Operasi
      arguments:
        gid:
          exception:
            title: Kabèh
  page_1:
    display_title: Kācā
