display:
  default:
    display_title: Gawan
    display_options:
      fields:
        comment_bulk_form:
          action_title: Aksi
        name:
          label: Penulis
        changed:
          label: 'Wis anyar'
        operations:
          label: Operasi
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- Kabeh -'
      exposed_form:
        options:
          reset_button_label: Baléknā
          sort_asc_label: 'Urut Maju'
          sort_desc_label: 'Urut Mundur'
      filters:
        langcode:
          expose:
            label: Basa
  page_unapproved:
    display_options:
      fields:
        comment_bulk_form:
          action_title: Aksi
        name:
          label: Penulis
        changed:
          label: 'Wis anyar'
        operations:
          label: Operasi
      filters:
        langcode:
          expose:
            label: Basa
