display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Baléknā
          sort_asc_label: 'Urut Maju'
          sort_desc_label: 'Urut Mundur'
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- Kabeh -'
      fields:
        order_id:
          label: ID
        placed:
          label: Tanggal
      arguments:
        uid:
          exception:
            title: Kabèh
