label: Konten
display:
  default:
    display_title: Gawan
    display_options:
      title: Konten
      fields:
        title:
          label: Judul
        type:
          label: 'Tipe kontèn'
        name:
          label: Penulis
        status:
          label: Status
          settings:
            format_custom_true: Dipacak
        changed:
          label: 'Wis anyar'
        operations:
          label: Operasi
      exposed_form:
        options:
          reset_button_label: Baléknā
          sort_asc_label: 'Urut Maju'
          sort_desc_label: 'Urut Mundur'
      empty:
        area_text_custom:
          content: 'Ora ānā kontèn sing cumawis.'
      filters:
        title:
          expose:
            label: Judul
        type:
          expose:
            label: 'Tipe kontèn'
        status:
          expose:
            label: Status
          group_info:
            group_items:
              1:
                title: Dipacak
        langcode:
          expose:
            label: Basa
  page_1:
    display_title: Kācā
    display_options:
      menu:
        title: Konten
      tab_options:
        title: Konten
