display:
  default:
    display_options:
      fields:
        is_default:
          label: Gawan
        name:
          label: Jeneng
        changed:
          label: 'Wis anyar'
        type:
          label: Tipe
        operations:
          label: Operasi
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- Kabeh -'
      exposed_form:
        options:
          reset_button_label: Baléknā
          sort_asc_label: 'Urut Maju'
          sort_desc_label: 'Urut Mundur'
      filters:
        type:
          expose:
            label: Tipe
  page_1:
    display_title: Kācā
