display:
  default:
    display_title: Gawan
    display_options:
      fields:
        name:
          label: 'Jeneng Panganggo'
        status:
          label: Status
          settings:
            format_custom_true: Aktif
        roles_target_id:
          label: Parāgā
        operations:
          label: Operasi
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- Kabeh -'
      exposed_form:
        options:
          reset_button_label: Baléknā
          sort_asc_label: 'Urut Maju'
          sort_desc_label: 'Urut Mundur'
      filters:
        status:
          group_info:
            label: Status
            group_items:
              1:
                title: Aktif
        roles_target_id:
          expose:
            label: Parāgā
        permission:
          expose:
            label: Kawenangan
  page_1:
    display_title: Kācā
    display_options:
      menu:
        title: Daftar
