content:
  field_anchor_menu_settings:
    settings:
      title: Paragraaf
      title_plural: Paragrafen
  field_tab:
    settings:
      title: Paragraaf
      title_plural: Paragrafen
  field_tooltip:
    settings:
      title: Paragraaf
      title_plural: Paragrafen
