third_party_settings:
  field_group:
    group_display_settings:
      label: Weergave-instellingen
content:
  field_filter_title:
    third_party_settings:
      maxlength:
        maxlength_js_label: 'Inhoud beperkt tot @limit tekens, resterend: <strong>@remaining</strong>'
  field_people_search:
    third_party_settings:
      maxlength:
        maxlength_js_label: 'Inhoud beperkt tot @limit tekens, resterend: <strong>@remaining</strong>'
