content:
  field_anchor_menu_settings:
    settings:
      title: Paragraaf
      title_plural: Paragrafen
  field_testimonial_component:
    settings:
      title: Paragraaf
      title_plural: Paragrafen
