display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Toepassen
          reset_button_label: Reset
          exposed_sorts_label: 'Sorteren op'
          sort_asc_label: Oplopend
          sort_desc_label: Aflopend
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« Eerste'
            last: 'Laatste »'
          expose:
            items_per_page_label: 'Items per pagina'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Offset
      fields:
        nid:
          separator: ', '
        delta:
          format_plural_string: !!binary MQNAY291bnQ=
        nothing:
          alter:
            text: Bewerken
        nothing_1:
          alter:
            text: Verwijderen
        title:
          label: Titel
          separator: ', '
        sp_dynamic:
          separator: ', '
        sp_dynamic_1:
          separator: ', '
        dropbutton:
          label: Bewerkingen
      filters:
        title:
          expose:
            label: Titel
  block_1:
    display_title: Blok
