content:
  field_body:
    third_party_settings:
      maxlength:
        maxlength_js_label: 'Обмеження матеріалу у символах - @limit, залишилось - <strong>@remaining</strong>'
  field_cta:
    settings:
      title_plural: Абзаци
  field_cta_secondary:
    settings:
      title_plural: Абзаци
