third_party_settings:
  field_group:
    group_display_settings:
      label: 'Налаштування відображення'
content:
  field_filter_title:
    third_party_settings:
      maxlength:
        maxlength_js_label: 'Обмеження матеріалу у символах - @limit, залишилось - <strong>@remaining</strong>'
  field_people_search:
    third_party_settings:
      maxlength:
        maxlength_js_label: 'Обмеження матеріалу у символах - @limit, залишилось - <strong>@remaining</strong>'
