label: Оплати
display:
  default:
    display_title: Базово
    display_options:
      title: Оплати
      fields:
        amount__number:
          label: Оплата
          separator: ', '
        refunded_amount__number:
          separator: ', '
        avs_response_code_label:
          separator: ', '
        avs_response_code:
          separator: ', '
        state:
          label: Стан
          separator: ', '
        payment_gateway:
          label: 'Шлюз оплати'
          separator: ', '
        authorized:
          label: Авторизовано
          separator: ', '
        completed:
          label: Завершено
          separator: ', '
        remote_id:
          label: 'Віддалений ID'
          separator: ', '
        operations:
          label: Операції
      exposed_form:
        options:
          submit_button: Застосувати
          reset_button_label: Скинути
          exposed_sorts_label: 'Впорядкувати за'
          sort_asc_label: Зрост
          sort_desc_label: Спад
      arguments:
        order_id:
          exception:
            title: Все
  page_1:
    display_title: Сторінка
    display_options:
      menu:
        title: Оплати
