display:
  default:
    display_title: Головне
    display_options:
      exposed_form:
        options:
          submit_button: Застосувати
          reset_button_label: Скинути
          exposed_sorts_label: 'Впорядкувати за'
          sort_asc_label: Зрост
          sort_desc_label: Спад
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« Перша'
            last: 'Остання »'
          expose:
            items_per_page_label: 'Елементів на сторінку'
            items_per_page_options_all_label: '- Усе -'
            offset_label: Зміщення
      fields:
        nid:
          separator: ', '
        delta:
          format_plural_string: !!binary QGNvdW50A0Bjb3VudANAY291bnQ=
        nothing:
          alter:
            text: Редагувати
        nothing_1:
          alter:
            text: Видалити
        title:
          label: Заголовок
          separator: ', '
        sp_dynamic:
          label: 'Час виконання'
          separator: ', '
        sp_dynamic_1:
          separator: ', '
        dropbutton:
          label: Операції
      filters:
        title:
          expose:
            label: Заголовок
  block_1:
    display_title: Блок
