display:
  default:
    display_title: 'Ana (master)'
    display_options:
      exposed_form:
        options:
          submit_button: Uygula
          reset_button_label: Sıfırla
          exposed_sorts_label: 'Sıralama anahtarı'
          sort_asc_label: Artan
          sort_desc_label: Azalan
      pager:
        options:
          tags:
            first: '« İlk'
            last: 'Son »'
          expose:
            items_per_page_label: 'Sayfa başına öğe sayısı'
            items_per_page_options_all_label: '- Tümü -'
            offset_label: 'Başlangıç değeri'
      fields:
        created:
          label: Oluşturulma
        remote_addr:
          label: 'IP adresi'
        view_webform_submission:
          label: İşlemler
      arguments:
        in_draft:
          exception:
            title: Tümü
  embed_administer:
    display_options:
      fields:
        webform_submission_bulk_form:
          action_title: Eylem
        locked:
          label: Kilitli
        created:
          label: Oluşturulma
        completed:
          label: Tamamlandı
        remote_addr:
          label: 'IP adresi'
        operations:
          label: İşlemler
      filters:
        locked:
          expose:
            label: Kilitli
  embed_manage:
    display_options:
      fields:
        webform_submission_bulk_form:
          action_title: Eylem
        locked:
          label: Kilitli
        created:
          label: Oluşturulma
        completed:
          label: Tamamlandı
        remote_addr:
          label: 'IP adresi'
        view_webform_submission:
          label: İşlemler
        edit_webform_submission:
          label: İşlemler
      filters:
        locked:
          expose:
            label: Kilitli
  embed_review:
    display_options:
      fields:
        locked:
          label: Kilitli
        created:
          label: Oluşturulma
        completed:
          label: Tamamlandı
        remote_addr:
          label: 'IP adresi'
        view_webform_submission:
          label: İşlemler
      filters:
        locked:
          expose:
            label: Kilitli
