label: Medya
display:
  default:
    display_title: Varsayılan
    display_options:
      title: Medya
      fields:
        media_bulk_form:
          action_title: Eylem
        bundle:
          label: Tip
        uid:
          label: Yazar
        status:
          label: Durum
          settings:
            format_custom_false: 'Yayında değil'
            format_custom_true: Yayında
        changed:
          label: Güncellendi
        operations:
          label: İşlemler
      pager:
        options:
          tags:
            first: '« İlk'
            last: 'Son »'
          expose:
            items_per_page_label: 'Sayfa başına öğe sayısı'
            items_per_page_options_all_label: '- Tümü -'
            offset_label: 'Başlangıç değeri'
      exposed_form:
        options:
          reset_button_label: Sıfırla
          exposed_sorts_label: 'Sıralama anahtarı'
          sort_asc_label: Artan
          sort_desc_label: Azalan
      filters:
        bundle:
          expose:
            label: Tip
        status:
          group_info:
            label: 'Yayın durumu'
            group_items:
              1:
                title: Yayında
              2:
                title: 'Yayında değil'
        langcode:
          expose:
            label: Dil
  media_page_list:
    display_title: Medya
    display_options:
      menu:
        title: Medya
