display:
  default:
    display_title: Varsayılan
    display_options:
      fields:
        completed:
          label: Tamamlandı
        operations:
          label: İşlemler
      exposed_form:
        options:
          submit_button: Uygula
          reset_button_label: Sıfırla
          exposed_sorts_label: 'Sıralama anahtarı'
          sort_asc_label: Artan
          sort_desc_label: Azalan
      arguments:
        order_id:
          exception:
            title: Tümü
  page_1:
    display_title: Sayfa
