display:
  default:
    display_title: 'Ana (master)'
    display_options:
      exposed_form:
        options:
          submit_button: Uygula
          reset_button_label: Sıfırla
          exposed_sorts_label: 'Sıralama anahtarı'
          sort_asc_label: Artan
          sort_desc_label: Azalan
      fields:
        title:
          label: Başlık
      arguments:
        order_item_id:
          exception:
            title: Tümü
