display:
  default:
    display_title: مدیر
    display_options:
      exposed_form:
        options:
          reset_button_label: بازنشانی
          exposed_sorts_label: 'مرتب کن بر اساس'
          sort_asc_label: صعودی
          sort_desc_label: نزولی
      pager:
        options:
          expose:
            items_per_page_label: 'آیتم‌ها در هر صفحه'
            items_per_page_options_all_label: '- همه -'
            offset_label: جابجایی
      fields:
        title:
          label: عنوان
        type:
          label: نوع
        status:
          label: وضعیت
          settings:
            format_custom_true: 'منتشر شده'
            format_custom_false: 'منتشر نشده'
        changed:
          label: به‌روز
        operations:
          label: عملیات
      filters:
        type:
          expose:
            label: نوع
        title:
          expose:
            label: عنوان
  page_1:
    display_title: صفحه
