display:
  default:
    display_title: پیش‌فرض
    display_options:
      fields:
        user_bulk_form:
          label: 'به‌روزرسانی جمعی'
        name:
          label: 'نام کاربری'
        status:
          label: وضعیت
          settings:
            format_custom_true: فعال
        roles_target_id:
          label: نقش‌ها
        operations:
          label: عملیات
      pager:
        options:
          expose:
            items_per_page_label: 'آیتم‌ها در هر صفحه'
            items_per_page_options_all_label: '- همه -'
            offset_label: جابجایی
      exposed_form:
        options:
          reset_button_label: بازنشانی
          exposed_sorts_label: 'مرتب کن بر اساس'
          sort_asc_label: صعودی
          sort_desc_label: نزولی
      filters:
        status:
          group_info:
            label: وضعیت
            group_items:
              1:
                title: فعال
        roles_target_id:
          expose:
            label: نقش
        permission:
          expose:
            label: مجوز
  page_1:
    display_title: صفحه
    display_options:
      menu:
        title: فهرست
