display:
  default:
    display_title: پیش‌فرض
    display_options:
      fields:
        filename:
          label: نام
        filesize:
          label: اندازه
        status:
          label: وضعیت
      pager:
        options:
          expose:
            items_per_page_label: 'آیتم‌ها در هر صفحه'
            items_per_page_options_all_label: '- همه -'
            offset_label: جابجایی
      exposed_form:
        options:
          reset_button_label: بازنشانی
          exposed_sorts_label: 'مرتب کن بر اساس'
          sort_asc_label: صعودی
          sort_desc_label: نزولی
      filters:
        filename:
          expose:
            label: 'نام فایل'
        status:
          expose:
            label: وضعیت
  page_2:
    display_options:
      fields:
        entity_label:
          label: عنصر
        type:
          label: 'نوع عنصر'
      pager:
        options:
          expose:
            items_per_page_label: 'آیتم‌ها در هر صفحه'
            items_per_page_options_all_label: '- همه -'
            offset_label: جابجایی
      arguments:
        fid:
          exception:
            title: همه
