content:
  field_body:
    third_party_settings:
      maxlength:
        maxlength_js_label: 'Pozostało znaków: <strong>@remaining</strong>/@limit.'
  field_cta:
    settings:
      title_plural: Akapity
  field_cta_secondary:
    settings:
      title_plural: Akapity
