content:
  field_anchor_menu_settings:
    settings:
      title: Akapit
      title_plural: Akapity
  field_paragraph:
    settings:
      title: Akapit
      title_plural: Akapity
  field_tooltip:
    settings:
      title: Akapit
      title_plural: Akapity
