display:
  default:
    display_title: Główny
    display_options:
      exposed_form:
        options:
          submit_button: Zastosuj
          reset_button_label: Resetuj
          exposed_sorts_label: 'Sortuj po'
          sort_asc_label: Rosnąco
          sort_desc_label: Malejąco
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« Pierwsza'
            last: 'Ostatnia »'
          expose:
            items_per_page_label: 'Elementów na stronę'
            items_per_page_options_all_label: '- Wszystko -'
            offset_label: Przesunięcie
      fields:
        nid:
          separator: ', '
        delta:
          format_plural_string: !!binary MQNAY291bnQDQGNvdW50
        nothing:
          alter:
            text: Edytuj
        nothing_1:
          alter:
            text: Usuń
        title:
          label: Tytuł
          separator: ', '
        sp_dynamic:
          separator: ', '
        sp_dynamic_1:
          separator: ', '
        dropbutton:
          label: Operacje
      filters:
        title:
          expose:
            label: Tytuł
  block_1:
    display_title: Blok
