settings:
  default_submit_button_label: Zachowaj
  default_reset_button_label: Resetuj
  default_delete_button_label: Usuń
  default_wizard_next_button_label: 'Następny >'
  default_wizard_start_label: Początek
  default_wizard_confirmation_label: Zakończone
  default_wizard_toggle_show_label: 'Pokaż wszystko'
  default_wizard_toggle_hide_label: 'Ukryj wszystko'
  default_preview_next_button_label: Podgląd
  default_preview_label: Podgląd
  default_draft_button_label: 'Zapisz szkic'
  default_draft_saved_message: 'Zgłoszenie zapisane. Możesz wrócić do tego formularza później, a wpisane wartości zostaną zapamiętane.'
  dialog_options:
    narrow:
      title: Wąskie
    normal:
      title: Zwykły
    wide:
      title: Szeroki
element:
  default_more_title: Więcej
  default_section_title_tag: h2
