display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Фильтрле
          reset_button_label: Ысыру
      pager:
        options:
          tags:
            previous: '‹ алдыңғы'
            next: 'келесі ›'
            first: "«\_бірінші"
            last: "соңғы\_»"
      fields:
        type:
          label: Тип
        operations:
          label: Операциялар
      filters:
        type:
          expose:
            label: Тип
  page_1:
    display_title: Бет
