display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Ысыру
      fields:
        remove_button:
          label: Өшіру
      arguments:
        order_id:
          exception:
            title: Барлық
