display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Ысыру
      fields:
        created:
          label: Құрылған
        view_webform_submission:
          label: Операциялар
          text: карау
      arguments:
        in_draft:
          exception:
            title: Барлық
  embed_administer:
    display_options:
      fields:
        webform_submission_bulk_form:
          action_title: Әрекет
        created:
          label: Құрылған
        operations:
          label: Операциялар
  embed_manage:
    display_options:
      fields:
        webform_submission_bulk_form:
          action_title: Әрекет
        created:
          label: Құрылған
        view_webform_submission:
          label: Операциялар
          text: карау
        edit_webform_submission:
          label: Операциялар
          text: түзету
  embed_review:
    display_options:
      fields:
        created:
          label: Құрылған
        view_webform_submission:
          label: Операциялар
          text: карау
