display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Ысыру
      fields:
        placed:
          label: Датасы
      arguments:
        uid:
          exception:
            title: Барлық
