display:
  default:
    display_title: Стандартты
    display_options:
      title: 'Кім онлайн'
      exposed_form:
        options:
          reset_button_label: Ысыру
      filters:
        access:
          expose:
            label: 'Соңғы қатынас'
            description: 'Пайдаланушы соңғы бетті көргеннен кейін осынша уақытқа онлайн болып саналады.'
  who_s_online_block:
    display_title: 'Кім онлайн'
    display_options:
      block_description: 'Кім онлайн'
