label: 'Кім жаңа?'
display:
  default:
    display_title: Стандартты
    display_options:
      title: 'Кім жаңа?'
      exposed_form:
        options:
          reset_button_label: Ысыру
  block_1:
    display_title: 'Кім жаңа?'
    display_options:
      block_description: 'Кім жаңа?'
      block_category: Пайдаланушы
