display:
  default:
    display_title: Стандартты
    display_options:
      fields:
        info:
          label: 'Блок сипаттамасы'
        operations:
          label: Операциялар
      exposed_form:
        options:
          reset_button_label: Ысыру
      filters:
        info:
          expose:
            label: 'Блок сипаттамасы'
  page_1:
    display_title: Бет
