display:
  default:
    display_title: Стандартты
    display_options:
      fields:
        operations:
          label: Операциялар
      exposed_form:
        options:
          reset_button_label: Ысыру
      arguments:
        order_id:
          exception:
            title: Барлық
  page_1:
    display_title: Бет
