label: Профильдер
display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Ысыру
      arguments:
        uid:
          exception:
            title: Барлық
        type:
          exception:
            title: Барлық
        status:
          exception:
            title: Барлық
      title: Профильдер
