display:
  default:
    display_options:
      fields:
        is_default:
          label: Стандартты
        name:
          label: Аты
        type:
          label: Тип
        operations:
          label: Операциялар
      pager:
        options:
          tags:
            next: 'келесі ›'
            previous: '‹ алдыңғы'
            first: "«\_бірінші"
            last: "соңғы\_»"
      exposed_form:
        options:
          reset_button_label: Ысыру
      filters:
        type:
          expose:
            label: Тип
  page_1:
    display_title: Бет
