display:
  default:
    display_title: Стандартты
    display_options:
      fields:
        media_bulk_form:
          action_title: Әрекет
        bundle:
          label: Тип
        uid:
          label: Автор
        status:
          label: Жағдайы
          settings:
            format_custom_true: Жарияланған
        operations:
          label: Операциялар
      exposed_form:
        options:
          submit_button: Фильтрле
          reset_button_label: Ысыру
      filters:
        bundle:
          expose:
            label: Тип
        status:
          group_info:
            group_items:
              1:
                title: Жарияланған
        langcode:
          expose:
            label: Тіл
