display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Ысыру
      fields:
        nothing:
          alter:
            text: Өңдеу
        nothing_1:
          alter:
            text: Өшіру
        title:
          label: Атауы
        dropbutton:
          label: Операциялар
      filters:
        title:
          expose:
            label: Атауы
  block_1:
    display_title: Блок
