label: 'Қосатын термин'
display:
  default:
    display_title: Стандартты
    display_options:
      exposed_form:
        options:
          reset_button_label: Ысыру
      arguments:
        tid:
          exception:
            title: Барлық
  page_1:
    display_title: Бет
