display:
  default:
    display_title: Стандартты
    display_options:
      fields:
        severity:
          label: Қауіптілік
        type:
          label: Тип
        timestamp:
          label: Датасы
        message:
          label: Хабарлама
        name:
          label: Пайдаланушы
        link:
          label: Операциялар
      exposed_form:
        options:
          submit_button: Фильтрле
          reset_button_label: Ысыру
      empty:
        area:
          admin_label: 'Жазба жоқ.'
          content: 'Жазба жоқ.'
      filters:
        type:
          expose:
            label: Тип
        severity:
          expose:
            label: Қауіптілік
  page:
    display_title: Бет
