label: 'Мазмұн модераторы'
display:
  default:
    display_title: Стандартты
    display_options:
      title: 'Мазмұн модераторы'
      fields:
        title:
          label: Атауы
        name:
          label: Автор
        operations:
          label: Операциялар
      exposed_form:
        options:
          submit_button: Фильтрле
          reset_button_label: Ысыру
      filters:
        title:
          expose:
            label: Атауы
        langcode:
          expose:
            label: Тіл
  moderated_content:
    display_title: 'Мазмұн модераторы'
