display:
  default:
    display_title: Стандартты
    display_options:
      fields:
        name:
          label: 'Қолданушының аты'
        status:
          label: Жағдайы
          settings:
            format_custom_false: Бұғатталған
            format_custom_true: Белсенді
        roles_target_id:
          label: Рөлдер
        created:
          label: 'Қатысу уақыты'
        access:
          label: 'Соңғы қатынас'
        operations:
          label: Операциялар
      exposed_form:
        options:
          submit_button: Фильтрле
          reset_button_label: Ысыру
      filters:
        status:
          group_info:
            label: Жағдайы
            group_items:
              1:
                title: Белсенді
              2:
                title: Бұғатталған
        permission:
          expose:
            label: Құқық
  page_1:
    display_title: Бет
    display_options:
      menu:
        title: Көрсету
