display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Фильтрле
          reset_button_label: Ысыру
      pager:
        options:
          tags:
            previous: '‹ алдыңғы'
            next: 'келесі ›'
            first: "«\_бірінші"
            last: "соңғы\_»"
      fields:
        redirect_source__path:
          label: Кімнен
        created:
          label: Құрылған
      filters:
        redirect_source__path:
          expose:
            label: Кімнен
        redirect_redirect__uri:
          expose:
            label: Қайда
  page_1:
    display_title: Бет
