display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Ысыру
      fields:
        title:
          label: Атауы
      arguments:
        order_item_id:
          exception:
            title: Барлық
