display:
  default:
    display_title: Стандартты
    display_options:
      fields:
        filename:
          label: Аты
        filesize:
          label: Көлем
        status:
          label: Жағдайы
      exposed_form:
        options:
          submit_button: Фильтрле
          reset_button_label: Ысыру
      filters:
        status:
          expose:
            label: Жағдайы
  page_2:
    display_options:
      arguments:
        fid:
          exception:
            title: Барлық
