display:
  default:
    display_title: Стандартты
    display_options:
      fields:
        media_bulk_form:
          action_title: Әрекет
      exposed_form:
        options:
          reset_button_label: Ысыру
      filters:
        status:
          group_info:
            label: Жарияланған
            group_items:
              1:
                title: Жарияланған
        name:
          expose:
            label: Аты
        langcode:
          expose:
            label: Тіл
  page:
    display_title: Бет
    display_options:
      fields:
        media_bulk_form:
          action_title: Әрекет
        edit_media:
          text: Өңдеу
        delete_media:
          text: Өшіру
  widget:
    display_options:
      arguments:
        bundle:
          exception:
            title: Барлық
      filters:
        name:
          expose:
            label: Аты
      header:
        display_link_table:
          label: Кесте
  widget_table:
    display_options:
      fields:
        name:
          label: Аты
        uid:
          label: Автор
      arguments:
        bundle:
          exception:
            title: Барлық
      filters:
        name:
          expose:
            label: Аты
      header:
        display_link_table:
          label: Кесте
