display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Фильтрле
          reset_button_label: Ысыру
      fields:
        code:
          label: Коды
        operations:
          label: Операциялар
      filters:
        code:
          expose:
            label: Коды
      arguments:
        promotion_id:
          exception:
            title: Барлық
  page_1:
    display_title: Бет
