content:
  field_anchor_menu_settings:
    settings:
      title_plural: Paragraphs
  field_carousel_card:
    settings:
      title_plural: Paragraphs
  field_tooltip:
    settings:
      title_plural: Paragraphs
