display:
  default:
    display_title: Nadřízené
    display_options:
      exposed_form:
        options:
          submit_button: Použít
          reset_button_label: Reset
          exposed_sorts_label: 'Řadit dle'
          sort_asc_label: Vzestupně
          sort_desc_label: Sestupně
      fields:
        title:
          label: Nadpis
          separator: ', '
        unit_price__number:
          label: 'Jednotková cena'
          separator: ', '
        quantity:
          label: Množství
          separator: ', '
        total_price__number:
          label: 'Celková cena'
          separator: ', '
      arguments:
        order_item_id:
          exception:
            title: Vše
