display:
  default:
    display_title: Nadřízené
    display_options:
      exposed_form:
        options:
          submit_button: Použít
          reset_button_label: Reset
          exposed_sorts_label: 'Řadit dle'
          sort_asc_label: Vzestupně
          sort_desc_label: Sestupně
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« První'
            last: 'Poslední »'
          expose:
            items_per_page_label: 'Položek na stránku'
            items_per_page_options_all_label: '- Vše -'
            offset_label: Posun
      fields:
        nid:
          separator: ', '
        delta:
          format_plural_string: !!binary MQNAY291bnQ=
        nothing:
          alter:
            text: Upravit
        nothing_1:
          alter:
            text: Smazat
        title:
          label: Nadpis
          separator: ', '
        sp_dynamic:
          separator: ', '
        sp_dynamic_1:
          separator: ', '
        dropbutton:
          label: Operace
      filters:
        title:
          expose:
            label: Nadpis
  block_1:
    display_title: Blok
