label: Objednávky
display:
  default:
    display_title: Nadřízené
    display_options:
      exposed_form:
        options:
          submit_button: Filtr
          reset_button_label: Reset
          exposed_sorts_label: 'Řadit dle'
          sort_asc_label: Vzestupně
          sort_desc_label: Sestupně
      pager:
        options:
          expose:
            items_per_page_label: 'Položek na stránku'
            items_per_page_options_all_label: '- Vše -'
            offset_label: Posun
          tags:
            previous: '‹ předchozí'
            next: 'následující ›'
            first: '« první'
            last: 'poslední »'
      fields:
        order_number:
          label: '#'
          separator: ', '
        placed:
          label: Datum
          separator: ', '
        type:
          label: Typ
          separator: ', '
        store_id:
          label: Obchod
          separator: ', '
        uid:
          label: Zákazník
          separator: ', '
        mail:
          label: E-mail
          separator: ', '
        state:
          label: Stav
          separator: ', '
        total_price__number:
          label: Celkem
          separator: ', '
        operations:
          label: Operace
      filters:
        order_number:
          expose:
            label: 'Číslo objednávky'
        type:
          expose:
            label: Typ
        state:
          expose:
            label: Stav
      title: Objednávky
  page_1:
    display_title: Stránka
    display_options:
      menu:
        title: Objednávky
      tab_options:
        title: Objednávky
