label: Profily
display:
  default:
    display_title: Nadřízené
    display_options:
      exposed_form:
        options:
          submit_button: Použít
          reset_button_label: Reset
          exposed_sorts_label: 'Řadit dle'
          sort_asc_label: Vzestupně
          sort_desc_label: Sestupně
      arguments:
        uid:
          exception:
            title: Vše
        type:
          exception:
            title: Vše
        status:
          exception:
            title: Vše
      title: Profily
  user_page:
    display_title: 'Stránka uživatele'
