label: Platby
display:
  default:
    display_title: Výchozí
    display_options:
      title: Platby
      fields:
        amount__number:
          label: Platba
          separator: ', '
        refunded_amount__number:
          separator: ', '
        avs_response_code_label:
          separator: ', '
        avs_response_code:
          separator: ', '
        state:
          label: Stav
          separator: ', '
        payment_gateway:
          separator: ', '
        authorized:
          label: Autorizován
          separator: ', '
        completed:
          label: Dokončené
          separator: ', '
        remote_id:
          label: 'Vzdálené ID'
          separator: ', '
        operations:
          label: Operace
      exposed_form:
        options:
          submit_button: Použít
          reset_button_label: Reset
          exposed_sorts_label: 'Řadit dle'
          sort_asc_label: Vzestupně
          sort_desc_label: Sestupně
      arguments:
        order_id:
          exception:
            title: Vše
  page_1:
    display_title: Stránka
    display_options:
      menu:
        title: Platby
