display:
  default:
    display_title: Nadřízené
    display_options:
      fields:
        is_default:
          label: Výchozí
          separator: ', '
        name:
          label: Jméno
          separator: ', '
        changed:
          label: Aktualizováno
          separator: ', '
        type:
          label: Typ
          separator: ', '
        operations:
          label: Operace
      pager:
        options:
          tags:
            next: 'následující ›'
            previous: '‹ předchozí'
            first: '« první'
            last: 'poslední »'
          expose:
            items_per_page_label: 'Položek na stránku'
            items_per_page_options_all_label: '- Vše -'
            offset_label: Posun
      exposed_form:
        options:
          submit_button: Použít
          reset_button_label: Reset
          exposed_sorts_label: 'Řadit dle'
          sort_asc_label: Vzestupně
          sort_desc_label: Sestupně
      filters:
        type:
          expose:
            label: Typ
  page_1:
    display_title: Stránka
