display:
  default:
    display_title: Výchozí
    display_options:
      exposed_form:
        options:
          submit_button: Použít
          reset_button_label: Reset
          exposed_sorts_label: 'Řadit dle'
          sort_asc_label: Vzestupně
          sort_desc_label: Sestupně
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« První'
            last: 'Poslední »'
          expose:
            items_per_page_label: 'Položek na stránku'
            items_per_page_options_all_label: '- Vše -'
            offset_label: Posun
      fields:
        name:
          label: Jméno
          separator: ', '
        offer__target_plugin_id:
          separator: ', '
        usage_limit:
          label: Použití
          separator: ', '
        usage_limit_customer:
          separator: ', '
        start_date:
          label: 'Datum začátku'
          separator: ', '
        end_date:
          label: 'Datum konce'
          separator: ', '
        operations:
          label: Operace
      filters:
        name:
          expose:
            label: Jméno
        code:
          expose:
            label: 'Kód kupónu'
        status:
          expose:
            label: Stav
  admin:
    display_title: Stránka
    display_options:
      menu:
        title: Seznam
      tab_options:
        title: Seznam
