display:
  default:
    display_title: Nadřízené
    display_options:
      exposed_form:
        options:
          submit_button: Použít
          reset_button_label: Reset
          exposed_sorts_label: 'Řadit dle'
          sort_asc_label: Vzestupně
          sort_desc_label: Sestupně
      pager:
        options:
          tags:
            previous: '‹ Předchozí'
            next: 'Následující ›'
            first: '« První'
            last: 'Poslední »'
          expose:
            items_per_page_label: 'Položek na stránku'
            items_per_page_options_all_label: '- Vše -'
            offset_label: Posun
      fields:
        order_id:
          label: ID
          separator: ', '
        order_number:
          label: 'Číslo objednávky'
          separator: ', '
        placed:
          label: Datum
          separator: ', '
        total_price__number:
          label: Celkem
          separator: ', '
        state:
          label: Stav
          separator: ', '
      title: Objednávky
      arguments:
        uid:
          exception:
            title: Vše
  order_page:
    display_options:
      menu:
        title: Objednávky
