display:
  default:
    display_title: Nadřízené
    display_options:
      exposed_form:
        options:
          submit_button: Použít
          reset_button_label: Reset
          exposed_sorts_label: 'Řadit dle'
          sort_asc_label: Vzestupně
          sort_desc_label: Sestupně
      fields:
        purchased_entity:
          label: Položka
          separator: ', '
        unit_price__number:
          label: Cena
          separator: ', '
        remove_button:
          label: Odstranit
        total_price__number:
          label: Celkem
          separator: ', '
      arguments:
        order_id:
          exception:
            title: Vše
