display:
  default:
    display_title: Основной
    display_options:
      fields:
        is_default:
          label: 'По умолчанию'
        name:
          label: Название
        changed:
          label: Обновлено
        type:
          label: Тип
        operations:
          label: Операции
      pager:
        options:
          expose:
            items_per_page_label: 'Элементов на страницу'
            items_per_page_options_all_label: '- Все -'
            offset_label: Пропустить
      exposed_form:
        options:
          submit_button: Применить
          reset_button_label: Сбросить
          exposed_sorts_label: 'Сортировать по'
          sort_asc_label: 'По возрастанию'
          sort_desc_label: 'По убыванию'
      filters:
        type:
          expose:
            label: Тип
  page_1:
    display_title: Страница
