display:
  default:
    display_title: 'По умолчанию'
    display_options:
      fields:
        comment_bulk_form:
          action_title: Действие
        name:
          label: Автор
        changed:
          label: Обновлено
        operations:
          label: Операции
      pager:
        options:
          expose:
            items_per_page_label: 'Элементов на страницу'
            items_per_page_options_all_label: '- Все -'
            offset_label: Пропустить
      exposed_form:
        options:
          reset_button_label: Сбросить
          exposed_sorts_label: 'Сортировать по'
          sort_asc_label: 'По возрастанию'
          sort_desc_label: 'По убыванию'
      filters:
        langcode:
          expose:
            label: Язык
  page_unapproved:
    display_options:
      fields:
        comment_bulk_form:
          action_title: Действие
        name:
          label: Автор
        changed:
          label: Обновлено
        operations:
          label: Операции
      filters:
        langcode:
          expose:
            label: Язык
