display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: ফিল্টার
      pager:
        options:
          tags:
            previous: '‹ পূর্ববর্তী'
            next: 'পরবর্তী ›'
            first: '« প্রথম'
            last: 'শেষ »'
      fields:
        title:
          label: শিরোনাম
        type:
          label: টাইপ
        status:
          label: স্ট্যাটাস
          settings:
            format_custom_true: প্রকাশিত
        changed:
          label: আপডেটকৃত
        operations:
          label: কার্যাবলী
      filters:
        type:
          expose:
            label: টাইপ
        title:
          expose:
            label: শিরোনাম
