display:
  default:
    display_options:
      fields:
        is_default:
          label: ডিফল্ট
        name:
          label: নাম
        changed:
          label: আপডেটকৃত
        type:
          label: টাইপ
        operations:
          label: কার্যাবলী
      pager:
        options:
          tags:
            next: 'পরবর্তী ›'
            previous: '‹ পূর্ববর্তী'
            first: '« প্রথম'
            last: 'শেষ »'
      filters:
        type:
          expose:
            label: টাইপ
