display:
  default:
    display_title: ডিফল্ট
    display_options:
      fields:
        operations:
          label: কার্যাবলী
      arguments:
        order_id:
          exception:
            title: সমস্ত
