display:
  default:
    display_title: الرئيسي
    display_options:
      exposed_form:
        options:
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      fields:
        code:
          label: الكود
        operations:
          label: عمليات
      filters:
        code:
          expose:
            label: الكود
      arguments:
        promotion_id:
          exception:
            title: الكل
  page_1:
    display_title: الصفحة
