display:
  default:
    display_title: الافتراضي
    display_options:
      fields:
        filename:
          label: الاسم
        filesize:
          label: الحجم
        status:
          label: الحالة
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      exposed_form:
        options:
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      filters:
        filename:
          expose:
            label: 'اسم الملف'
        status:
          expose:
            label: الحالة
  page_2:
    display_options:
      fields:
        entity_label:
          label: الكيان
        type:
          label: 'نوع الكيان'
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      arguments:
        fid:
          exception:
            title: الكل
