display:
  default:
    display_title: الافتراضي
    display_options:
      fields:
        completed:
          label: 'تم الإنهاء'
        operations:
          label: عمليات
      exposed_form:
        options:
          submit_button: تطبيق
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      arguments:
        order_id:
          exception:
            title: الكل
  page_1:
    display_title: الصفحة
