label: Kandungan
display:
  default:
    display_title: Lalai
    display_options:
      title: Kandungan
      fields:
        title:
          label: Tajuk
        type:
          label: 'Jenis kandungan'
        name:
          label: Pengarang
        status:
          label: Status
          settings:
            format_custom_false: 'Belum diterbitkan'
            format_custom_true: Diterbitkan
        changed:
          label: 'Telah dikemaskinikan'
        operations:
          label: Operasi-operasi
      exposed_form:
        options:
          reset_button_label: 'Set semula'
          exposed_sorts_label: 'Susun mengikuti'
          sort_asc_label: Menaik
          sort_desc_label: Menurun
      empty:
        area_text_custom:
          content: 'Tiada kandungan tersedia ada.'
      filters:
        title:
          expose:
            label: Tajuk
        type:
          expose:
            label: 'Jenis kandungan'
        status:
          expose:
            label: Status
          group_info:
            group_items:
              1:
                title: Diterbitkan
              2:
                title: 'Belum diterbitkan'
        langcode:
          expose:
            label: Bahasa
  page_1:
    display_title: Halaman
    display_options:
      menu:
        title: Kandungan
      tab_options:
        title: Kandungan
