display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Pohon
          reset_button_label: 'Set semula'
          exposed_sorts_label: 'Susun mengikuti'
          sort_asc_label: Menaik
          sort_desc_label: Menurun
      pager:
        options:
          expose:
            items_per_page_label: 'Item per halaman'
            items_per_page_options_all_label: '- Semua -'
      fields:
        name:
          label: Pengguna
        group_roles:
          label: Peranan
        changed:
          label: 'Telah dikemaskinikan'
        dropbutton:
          label: Operasi-operasi
      arguments:
        gid:
          exception:
            title: Semua
  page_1:
    display_title: Halaman
