display:
  default:
    display_title: Lalai
    display_options:
      fields:
        title:
          label: Tajuk
        name:
          label: Pengarang
      pager:
        options:
          expose:
            items_per_page_label: 'Item per halaman'
            items_per_page_options_all_label: '- Semua -'
      exposed_form:
        options:
          submit_button: Pohon
          reset_button_label: 'Set semula'
          exposed_sorts_label: 'Susun mengikuti'
          sort_asc_label: Menaik
          sort_desc_label: Menurun
  page_1:
    display_title: Halaman
