display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Pohon
          reset_button_label: 'Set semula'
          exposed_sorts_label: 'Susun mengikuti'
          sort_asc_label: Menaik
          sort_desc_label: Menurun
      arguments:
        uid:
          exception:
            title: Semua
        type:
          exception:
            title: Semua
        status:
          exception:
            title: Semua
