label: Media
display:
  default:
    display_title: Lalai
    display_options:
      title: Media
      fields:
        media_bulk_form:
          action_title: Tindakan
        bundle:
          label: Jenis
        uid:
          label: Pengarang
        status:
          label: Status
          settings:
            format_custom_false: 'Belum diterbitkan'
            format_custom_true: Diterbitkan
        changed:
          label: 'Telah dikemaskinikan'
        operations:
          label: Operasi-operasi
      pager:
        options:
          expose:
            items_per_page_label: 'Item per halaman'
            items_per_page_options_all_label: '- Semua -'
      exposed_form:
        options:
          reset_button_label: 'Set semula'
          exposed_sorts_label: 'Susun mengikuti'
          sort_asc_label: Menaik
          sort_desc_label: Menurun
      filters:
        bundle:
          expose:
            label: Jenis
        status:
          group_info:
            group_items:
              1:
                title: Diterbitkan
              2:
                title: 'Belum diterbitkan'
        langcode:
          expose:
            label: Bahasa
  media_page_list:
    display_title: Media
    display_options:
      menu:
        title: Media
