display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Pohon
          reset_button_label: 'Set semula'
          exposed_sorts_label: 'Susun mengikuti'
          sort_asc_label: Menaik
          sort_desc_label: Menurun
      fields:
        remove_button:
          label: Buang
      arguments:
        order_id:
          exception:
            title: Semua
