display:
  default:
    display_title: Lalai
    display_options:
      exposed_form:
        options:
          submit_button: Pohon
          reset_button_label: 'Set semula'
          exposed_sorts_label: 'Susun mengikuti'
          sort_asc_label: Menaik
          sort_desc_label: Menurun
      pager:
        options:
          expose:
            items_per_page_label: 'Item per halaman'
            items_per_page_options_all_label: '- Semua -'
      fields:
        name:
          label: Nama
        operations:
          label: Operasi-operasi
      filters:
        name:
          expose:
            label: Nama
        status:
          expose:
            label: Status
  admin:
    display_title: Halaman
    display_options:
      menu:
        title: Senarai
      tab_options:
        title: Senarai
