display:
  default:
    display_title: Lalai
    display_options:
      fields:
        title:
          label: Tajuk
        type:
          label: 'Jenis kandungan'
        name:
          label: Pengarang
        changed:
          label: 'Telah dikemaskinikan'
        operations:
          label: Operasi-operasi
      pager:
        options:
          expose:
            items_per_page_label: 'Item per halaman'
            items_per_page_options_all_label: '- Semua -'
      exposed_form:
        options:
          reset_button_label: 'Set semula'
          exposed_sorts_label: 'Susun mengikuti'
          sort_asc_label: Menaik
          sort_desc_label: Menurun
      filters:
        title:
          expose:
            label: Tajuk
        type:
          expose:
            label: 'Jenis kandungan'
        langcode:
          expose:
            label: Bahasa
