display:
  default:
    display_title: Lalai
    display_options:
      fields:
        type:
          label: Jenis
        timestamp:
          label: Tarikh
        message:
          label: Mesej
        name:
          label: Pengguna
        link:
          label: Operasi-operasi
      pager:
        options:
          expose:
            items_per_page_label: 'Item per halaman'
            items_per_page_options_all_label: '- Semua -'
      exposed_form:
        options:
          reset_button_label: 'Set semula'
          exposed_sorts_label: 'Susun mengikuti'
          sort_asc_label: Menaik
          sort_desc_label: Menurun
      filters:
        type:
          expose:
            label: Jenis
  page:
    display_title: Halaman
