display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: 'Set semula'
          exposed_sorts_label: 'Susun mengikuti'
          sort_asc_label: Menaik
          sort_desc_label: Menurun
      pager:
        options:
          expose:
            items_per_page_label: 'Item per halaman'
            items_per_page_options_all_label: '- Semua -'
      fields:
        code:
          label: Kod
        operations:
          label: Operasi-operasi
      filters:
        code:
          expose:
            label: Kod
      arguments:
        promotion_id:
          exception:
            title: Semua
  page_1:
    display_title: Halaman
