display:
  default:
    display_title: Lalai
    display_options:
      fields:
        operations:
          label: Operasi-operasi
      exposed_form:
        options:
          submit_button: Pohon
          reset_button_label: 'Set semula'
          exposed_sorts_label: 'Susun mengikuti'
          sort_asc_label: Menaik
          sort_desc_label: Menurun
      arguments:
        order_id:
          exception:
            title: Semua
  page_1:
    display_title: Halaman
