display:
  default:
    display_title: 'طے شدہ'
    display_options:
      fields:
        operations:
          label: معاملات
      exposed_form:
        options:
          exposed_sorts_label: 'کی طرف سے  کی گئی مرتب سازی'
