display:
  default:
    display_title: 'طے شدہ'
    display_options:
      exposed_form:
        options:
          exposed_sorts_label: 'کی طرف سے  کی گئی مرتب سازی'
      pager:
        options:
          tags:
            previous: ››
            next: ‹‹
            first: '» ابتدائی'
      fields:
        operations:
          label: معاملات
      filters:
        status:
          expose:
            label: حالت
  admin:
    display_options:
      menu:
        title: فہرست
      tab_options:
        title: فہرست
