display:
  default:
    display_options:
      fields:
        is_default:
          label: 'طے شدہ'
        type:
          label: قِسم
        operations:
          label: معاملات
      pager:
        options:
          tags:
            next: اگلا>
            previous: '› گزشتہ'
            first: '» ابتدائی'
            last: 'آخری »'
      exposed_form:
        options:
          exposed_sorts_label: 'کی طرف سے  کی گئی مرتب سازی'
      filters:
        type:
          expose:
            label: قِسم
