display:
  default:
    display_options:
      exposed_form:
        options:
          exposed_sorts_label: 'کی طرف سے  کی گئی مرتب سازی'
      pager:
        options:
          tags:
            previous: ››
            next: ‹‹
            first: '» ابتدائی'
      fields:
        nothing_1:
          alter:
            text: 'حذف کریں'
        title:
          label: عنوان
        dropbutton:
          label: معاملات
      filters:
        title:
          expose:
            label: عنوان
  block_1:
    display_title: بلاک
