display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: فلٹر
          exposed_sorts_label: 'کی طرف سے  کی گئی مرتب سازی'
      pager:
        options:
          tags:
            previous: '› گزشتہ'
            next: اگلا>
            first: '» ابتدائی'
            last: 'آخری »'
      fields:
        type:
          label: قِسم
        mail:
          label: 'ای میل'
        operations:
          label: معاملات
      filters:
        type:
          expose:
            label: قِسم
