display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: မူလပုံစံအတိုင်းပြန်ထားရန်
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- အားလုံး -'
      fields:
        sid:
          label: '#'
        remote_addr:
          label: 'IP လိပ်စာ'
        view_webform_submission:
          label: လုပ်ဆောင်ချက်များ
          text: မြင်ကွင်း
  embed_administer:
    display_options:
      fields:
        webform_submission_bulk_form:
          action_title: 'လုပ်ဆောင်ရန် (လုပ်ဆောင်ချက်)'
        sid:
          label: '#'
        locked:
          label: ပိတ်ထားသည်
        completed:
          label: ပြီးဆုံးပါပြီ
        remote_addr:
          label: 'IP လိပ်စာ'
        operations:
          label: လုပ်ဆောင်ချက်များ
      filters:
        locked:
          expose:
            label: ပိတ်ထားသည်
  embed_manage:
    display_options:
      fields:
        webform_submission_bulk_form:
          action_title: 'လုပ်ဆောင်ရန် (လုပ်ဆောင်ချက်)'
        sid:
          label: '#'
        locked:
          label: ပိတ်ထားသည်
        completed:
          label: ပြီးဆုံးပါပြီ
        remote_addr:
          label: 'IP လိပ်စာ'
        view_webform_submission:
          label: လုပ်ဆောင်ချက်များ
          text: မြင်ကွင်း
        edit_webform_submission:
          label: လုပ်ဆောင်ချက်များ
          text: ပြင်ရန်
      filters:
        locked:
          expose:
            label: ပိတ်ထားသည်
  embed_review:
    display_options:
      fields:
        sid:
          label: '#'
        locked:
          label: ပိတ်ထားသည်
        completed:
          label: ပြီးဆုံးပါပြီ
        remote_addr:
          label: 'IP လိပ်စာ'
        view_webform_submission:
          label: လုပ်ဆောင်ချက်များ
          text: မြင်ကွင်း
      filters:
        locked:
          expose:
            label: ပိတ်ထားသည်
