display:
  default:
    display_title: Default
    display_options:
      fields:
        filename:
          label: အမည်
        filesize:
          label: အရွယ်အစား
        status:
          label: အခြေအနေ
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- အားလုံး -'
      exposed_form:
        options:
          reset_button_label: မူလပုံစံအတိုင်းပြန်ထားရန်
      filters:
        filename:
          expose:
            label: ဖိုင်အမည်
        status:
          expose:
            label: အခြေအနေ
  page_2:
    display_options:
      fields:
        count:
          label: 'အသုံးပြုမှု အရေအတွက်'
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- အားလုံး -'
