display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: မူလပုံစံအတိုင်းပြန်ထားရန်
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- အားလုံး -'
      fields:
        code:
          label: Code
        operations:
          label: လုပ်ဆောင်ချက်များ
      filters:
        code:
          expose:
            label: Code
  page_1:
    display_title: စာမျက်နှာ
