display:
  default:
    display_title: Default
    display_options:
      fields:
        info:
          label: 'block အကြောင်းအရာဖော်ပြချက်'
        operations:
          label: လုပ်ဆောင်ချက်များ
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- အားလုံး -'
      exposed_form:
        options:
          reset_button_label: မူလပုံစံအတိုင်းပြန်ထားရန်
      filters:
        info:
          expose:
            label: 'block အကြောင်းအရာဖော်ပြချက်'
  page_1:
    display_title: စာမျက်နှာ
