display:
  default:
    display_options:
      fields:
        is_default:
          label: Default
        name:
          label: အမည်
        type:
          label: အမျိုးအစား
        operations:
          label: လုပ်ဆောင်ချက်များ
      pager:
        options:
          tags:
            next: 'နောက် ›'
            previous: '‹ ယခင်'
            first: '« ပထမ'
            last: 'နောက်ဆုံး ›'
          expose:
            items_per_page_options_all_label: '- အားလုံး -'
      exposed_form:
        options:
          reset_button_label: မူလပုံစံအတိုင်းပြန်ထားရန်
      filters:
        type:
          expose:
            label: အမျိုးအစား
  page_1:
    display_title: စာမျက်နှာ
