label: 'Taxonomy အသုံးအနှုံး'
display:
  default:
    display_title: Default
    display_options:
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- အားလုံး -'
      exposed_form:
        options:
          reset_button_label: မူလပုံစံအတိုင်းပြန်ထားရန်
  page_1:
    display_title: စာမျက်နှာ
