display:
  default:
    display_title: Default
    display_options:
      title: ရောက်ရှိနေသူများ
      exposed_form:
        options:
          reset_button_label: မူလပုံစံအတိုင်းပြန်ထားရန်
  who_s_online_block:
    display_title: ရောက်ရှိနေသူများ
    display_options:
      block_description: ရောက်ရှိနေသူများ
