display:
  default:
    display_title: Default
    display_options:
      title: မီဒီယာ
      fields:
        media_bulk_form:
          action_title: 'လုပ်ဆောင်ရန် (လုပ်ဆောင်ချက်)'
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- အားလုံး -'
      exposed_form:
        options:
          reset_button_label: မူလပုံစံအတိုင်းပြန်ထားရန်
      sorts:
        created:
          expose:
            label: 'အသစ်များကို အရင်ဆုံး'
      filters:
        status:
          group_info:
            label: 'Publish လုပ်ပြီး'
            group_items:
              1:
                title: 'Publish လုပ်ပြီး'
        name:
          expose:
            label: အမည်
        langcode:
          expose:
            label: ဘာသာစကား
  page:
    display_title: စာမျက်နှာ
    display_options:
      fields:
        media_bulk_form:
          action_title: 'လုပ်ဆောင်ရန် (လုပ်ဆောင်ချက်)'
        edit_media:
          text: ပြင်ရန်
        delete_media:
          text: ပယ်ဖျက်
  widget:
    display_options:
      filters:
        name:
          expose:
            label: အမည်
      header:
        display_link_table:
          label: ဇယား
  widget_table:
    display_options:
      fields:
        name:
          label: အမည်
        uid:
          label: စာရေးသူ
      filters:
        name:
          expose:
            label: အမည်
      header:
        display_link_table:
          label: ဇယား
