display:
  default:
    display_title: Default
    display_options:
      exposed_form:
        options:
          reset_button_label: မူလပုံစံအတိုင်းပြန်ထားရန်
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- အားလုံး -'
      fields:
        name:
          label: အမည်
        operations:
          label: လုပ်ဆောင်ချက်များ
      filters:
        name:
          expose:
            label: အမည်
        status:
          expose:
            label: အခြေအနေ
  admin:
    display_title: စာမျက်နှာ
    display_options:
      menu:
        title: စာရင်း
      tab_options:
        title: စာရင်း
