label: 'လတ်တလော အကြောင်းအရာများ'
display:
  default:
    display_title: Default
    display_options:
      title: 'လတ်တလော အကြောင်းအရာများ'
      exposed_form:
        options:
          reset_button_label: မူလပုံစံအတိုင်းပြန်ထားရန်
      use_more_text: ပို၍
