label: လူများ
display:
  default:
    display_title: Default
    display_options:
      title: လူများ
      fields:
        name:
          label: အမည်
        status:
          label: အခြေအနေ
        roles_target_id:
          label: အဆင့်သတ်မှတ်ချက်များ
        created:
          label: အသင်း၀င်ဖြစ်ခဲ့သည့်ကာလ
        operations:
          label: လုပ်ဆောင်ချက်များ
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- အားလုံး -'
      exposed_form:
        options:
          reset_button_label: မူလပုံစံအတိုင်းပြန်ထားရန်
      filters:
        status:
          group_info:
            label: အခြေအနေ
      use_more_text: ပို၍
  page_1:
    display_title: စာမျက်နှာ
    display_options:
      menu:
        title: စာရင်း
      tab_options:
        title: လူများ
        description: 'User account များ၊အဆင့်အတန်းများနှင့် လုပ်ပိုင်ခွင့်များကို စီမံခန့်ခွဲရန်'
