display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: မူလပုံစံအတိုင်းပြန်ထားရန်
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- အားလုံး -'
      fields:
        nothing:
          alter:
            text: ပြင်ရန်
        nothing_1:
          alter:
            text: ပယ်ဖျက်
        title:
          label: ခေါင်းစဉ်
        dropbutton:
          label: လုပ်ဆောင်ချက်များ
      filters:
        title:
          expose:
            label: ခေါင်းစဉ်
