display:
  default:
    display_title: Default
    display_options:
      fields:
        title:
          label: ခေါင်းစဉ်
        type:
          label: အကြောင်းအရာအမျိုးအစား
        name:
          label: စာရေးသူ
        operations:
          label: လုပ်ဆောင်ချက်များ
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- အားလုံး -'
      exposed_form:
        options:
          reset_button_label: မူလပုံစံအတိုင်းပြန်ထားရန်
      filters:
        title:
          expose:
            label: ခေါင်းစဉ်
        type:
          expose:
            label: အကြောင်းအရာအမျိုးအစား
        langcode:
          expose:
            label: ဘာသာစကား
