label: အကြောင်းအရာ
display:
  default:
    display_title: Default
    display_options:
      title: အကြောင်းအရာ
      fields:
        title:
          label: ခေါင်းစဉ်
        type:
          label: အကြောင်းအရာအမျိုးအစား
        name:
          label: စာရေးသူ
        status:
          label: အခြေအနေ
          settings:
            format_custom_true: 'Publish လုပ်ပြီး'
        operations:
          label: လုပ်ဆောင်ချက်များ
      exposed_form:
        options:
          reset_button_label: မူလပုံစံအတိုင်းပြန်ထားရန်
      filters:
        title:
          expose:
            label: ခေါင်းစဉ်
        type:
          expose:
            label: အကြောင်းအရာအမျိုးအစား
        status:
          expose:
            label: အခြေအနေ
          group_info:
            group_items:
              1:
                title: 'Publish လုပ်ပြီး'
        langcode:
          expose:
            label: ဘာသာစကား
  page_1:
    display_title: စာမျက်နှာ
    display_options:
      menu:
        title: အကြောင်းအရာ
      tab_options:
        title: အကြောင်းအရာ
