display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: မူလပုံစံအတိုင်းပြန်ထားရန်
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- အားလုံး -'
      fields:
        name:
          label: အသုံးပြုသူ
        group_roles:
          label: အဆင့်သတ်မှတ်ချက်များ
        dropbutton:
          label: လုပ်ဆောင်ချက်များ
  page_1:
    display_title: စာမျက်နှာ
