label: အသင်း၀င်သစ်များ
display:
  default:
    display_title: Default
    display_options:
      title: အသင်း၀င်သစ်များ
      exposed_form:
        options:
          reset_button_label: မူလပုံစံအတိုင်းပြန်ထားရန်
  block_1:
    display_title: အသင်း၀င်သစ်များ
    display_options:
      block_description: အသင်း၀င်သစ်များ
      block_category: အသုံးပြုသူ
