settings:
  default_submit_button_label: တင်သွင်းသည်
  default_reset_button_label: မူလပုံစံအတိုင်းပြန်ထားရန်
  default_delete_button_label: ပယ်ဖျက်
  default_preview_next_button_label: အစမ်းကြည့်ရန်
  default_preview_label: အစမ်းကြည့်ရန်
  dialog_options:
    normal:
      title: ပုံမှန်
element:
  default_more_title: ပို၍
