content:
  field_anchor_menu_settings:
    settings:
      title: Seitenabschnitt
      title_plural: Seitenabschnitte
  field_testimonial_component:
    settings:
      title: Seitenabschnitt
      title_plural: Seitenabschnitte
