third_party_settings:
  field_group:
    group_cards:
      label: Karten
content:
  field_anchor_menu_settings:
    settings:
      title: Seitenabschnitt
      title_plural: Seitenabschnitte
  field_card_group:
    settings:
      title: Seitenabschnitt
      title_plural: Seitenabschnitte
  field_cta:
    settings:
      title: Seitenabschnitt
      title_plural: Seitenabschnitte
  field_tooltip:
    settings:
      title: Seitenabschnitt
      title_plural: Seitenabschnitte
