third_party_settings:
  field_group:
    group_display_settings:
      label: Anzeigeeinstellungen
content:
  field_filter_title:
    third_party_settings:
      maxlength:
        maxlength_js_label: 'Eingabe begrenzt auf @limit Zeichen, verbleibend: <strong>@remaining</strong>'
  field_people_search:
    third_party_settings:
      maxlength:
        maxlength_js_label: 'Eingabe begrenzt auf @limit Zeichen, verbleibend: <strong>@remaining</strong>'
