content:
  field_anchor_menu_settings:
    settings:
      title: Seitenabschnitt
      title_plural: Seitenabschnitte
  field_card:
    settings:
      title: Seitenabschnitt
      title_plural: Seitenabschnitte
