label: Shops
display:
  default:
    display_title: Master
    display_options:
      title: Shops
      fields:
        commerce_store_bulk_form:
          action_title: 'Mit Auswahl'
        is_default:
          label: Standard
          separator: ', '
        name:
          label: Name
          separator: ', '
        changed:
          label: Aktualisiert
          separator: ', '
        type:
          label: Typ
          separator: ', '
        operations:
          label: Aktionen
      pager:
        options:
          tags:
            next: 'nächste Seite ›'
            previous: '‹ vorherige Seite'
            first: '« erste Seite'
            last: 'letzte Seite »'
          expose:
            items_per_page_label: 'Elemente pro Seite'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Versatz
      exposed_form:
        options:
          submit_button: Anwenden
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      filters:
        type:
          expose:
            label: Typ
  page_1:
    display_title: Seite
