display:
  default:
    display_title: મૂળભૂત
    display_options:
      fields:
        media_bulk_form:
          action_title: ક્રિયા
        thumbnail__target_id:
          separator: ', '
        name:
          separator: ', '
        bundle:
          label: પ્રકાર
          separator: ', '
        uid:
          label: લેખક
          separator: ', '
        status:
          label: સ્થિતિ
          settings:
            format_custom_true: પ્રકાશિત
          separator: ', '
        changed:
          label: 'અધતન થયું'
          separator: ', '
        operations:
          label: ક્રિયાઓ
      exposed_form:
        options:
          submit_button: ફિલ્ટર
      filters:
        bundle:
          expose:
            label: પ્રકાર
        status:
          expose:
            label: સાચું
          group_info:
            group_items:
              1:
                title: પ્રકાશિત
        langcode:
          expose:
            label: ભાષા
