display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: ફિલ્ટર
      fields:
        title:
          label: શિર્ષક
          separator: ', '
        type:
          label: પ્રકાર
          separator: ', '
        status:
          label: સ્થિતિ
          settings:
            format_custom_true: પ્રકાશિત
          separator: ', '
        changed:
          label: 'અધતન થયું'
          separator: ', '
        operations:
          label: ક્રિયાઓ
      filters:
        type:
          expose:
            label: પ્રકાર
        title:
          expose:
            label: શિર્ષક
  page_1:
    display_title: પ્રુષ્ઠ
