display:
  default:
    display_title: મૂળભૂત
    display_options:
      fields:
        title:
          label: શિર્ષક
          separator: ', '
        type:
          separator: ', '
        name:
          label: લેખક
          separator: ', '
        moderation_state:
          separator: ', '
        changed:
          label: 'અધતન થયું'
          separator: ', '
        operations:
          label: ક્રિયાઓ
      exposed_form:
        options:
          submit_button: ફિલ્ટર
      filters:
        title:
          expose:
            label: શિર્ષક
        langcode:
          expose:
            label: ભાષા
