display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: 'લાગુ કરો'
      fields:
        purchased_entity:
          label: નંગ
          separator: ', '
        unit_price__number:
          separator: ', '
        remove_button:
          label: લોપ
        total_price__number:
          separator: ', '
      arguments:
        order_id:
          exception:
            title: બધા
