display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: ફિલ્ટર
      fields:
        code:
          separator: ', '
        usage_limit:
          separator: ', '
        usage_limit_customer:
          separator: ', '
        operations:
          label: ક્રિયાઓ
      arguments:
        promotion_id:
          exception:
            title: બધા
  page_1:
    display_title: પ્રુષ્ઠ
