display:
  default:
    display_title: મૂળભૂત
    display_options:
      exposed_form:
        options:
          submit_button: 'લાગુ કરો'
      fields:
        name:
          label: નામ
          separator: ', '
        offer__target_plugin_id:
          separator: ', '
        usage_limit:
          separator: ', '
        usage_limit_customer:
          separator: ', '
        start_date:
          separator: ', '
        end_date:
          separator: ', '
        operations:
          label: ક્રિયાઓ
      filters:
        name:
          expose:
            label: નામ
        status:
          expose:
            label: સ્થિતિ
  admin:
    display_title: પ્રુષ્ઠ
    display_options:
      menu:
        title: સૂચિ
      tab_options:
        title: સૂચિ
