display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: 'લાગુ કરો'
      fields:
        title:
          label: શિર્ષક
          separator: ', '
        unit_price__number:
          separator: ', '
        quantity:
          separator: ', '
        total_price__number:
          separator: ', '
      arguments:
        order_item_id:
          exception:
            title: બધા
