display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: 'લાગુ કરો'
      fields:
        quantity:
          separator: ', '
        purchased_entity:
          separator: ', '
        total_price__number:
          separator: ', '
      arguments:
        order_id:
          exception:
            title: બધા
