display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: 'લાગુ કરો'
      fields:
        order_id:
          label: ID
          separator: ', '
        order_number:
          separator: ', '
        placed:
          label: તારીખ
          separator: ', '
        total_price__number:
          separator: ', '
        state:
          separator: ', '
      arguments:
        uid:
          exception:
            title: બધા
