display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: 'લાગુ કરો'
      fields:
        nid:
          separator: ', '
        nothing:
          alter:
            text: 'સંપાદિત કરો'
        nothing_1:
          alter:
            text: 'કાઢી નાખો'
        title:
          label: શિર્ષક
          separator: ', '
        sp_dynamic:
          separator: ', '
        sp_dynamic_1:
          separator: ', '
        dropbutton:
          label: ક્રિયાઓ
      filters:
        title:
          expose:
            label: શિર્ષક
