display:
  default:
    display_title: 'Par défaut'
    display_options:
      exposed_form:
        options:
          submit_button: Appliquer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
      pager:
        options:
          tags:
            first: '« Premier'
            last: 'Dernier »'
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      fields:
        name:
          label: Nom
        operations:
          label: Actions
      filters:
        name:
          expose:
            label: Nom
        status:
          expose:
            label: État
  admin:
    display_options:
      menu:
        title: Lister
      tab_options:
        title: Lister
