display:
  default:
    display_title: 'Par défaut'
    display_options:
      fields:
        completed:
          label: Terminé
        operations:
          label: Actions
      exposed_form:
        options:
          submit_button: Appliquer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
      arguments:
        order_id:
          exception:
            title: Tout
