label: Média
display:
  default:
    display_title: 'Par défaut'
    display_options:
      title: Média
      fields:
        bundle:
          label: Type
        uid:
          label: Auteur
        status:
          label: État
          settings:
            format_custom_false: 'Non publié'
            format_custom_true: Publié
        changed:
          label: 'Mis à jour'
        operations:
          label: Actions
      pager:
        options:
          tags:
            first: '« Premier'
            last: 'Dernier »'
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      exposed_form:
        options:
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
      filters:
        bundle:
          expose:
            label: Type
        status:
          group_info:
            label: 'Statut de publication'
            group_items:
              1:
                title: Publié
              2:
                title: 'Non publié'
        langcode:
          expose:
            label: Langue
  media_page_list:
    display_title: Média
    display_options:
      menu:
        title: Média
