display:
  default:
    display_title: Maître
    display_options:
      exposed_form:
        options:
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
      pager:
        options:
          tags:
            first: '« Premier'
            last: 'Dernier »'
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      fields:
        code:
          label: Code
        operations:
          label: Actions
      filters:
        code:
          expose:
            label: Code
      arguments:
        promotion_id:
          exception:
            title: Tout
