display:
  default:
    display_title: Maître
    display_options:
      exposed_form:
        options:
          submit_button: Appliquer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
      pager:
        options:
          tags:
            first: '« Premier'
            last: 'Dernier »'
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      fields:
        nothing:
          alter:
            text: Modifier
        nothing_1:
          alter:
            text: Supprimer
        title:
          label: Titre
        dropbutton:
          label: Actions
      filters:
        title:
          expose:
            label: Titre
