display:
  default:
    display_title: 'Par défaut'
    display_options:
      fields:
        filename:
          label: Nom
        filesize:
          label: Taille
        status:
          label: État
      pager:
        options:
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      exposed_form:
        options:
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
      filters:
        filename:
          expose:
            label: 'Nom du fichier'
        status:
          expose:
            label: État
  page_2:
    display_options:
      fields:
        entity_label:
          label: Entité
        type:
          label: 'Type d''entité'
      pager:
        options:
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      arguments:
        fid:
          exception:
            title: Tout
