display:
  default:
    display_title: 'Par défaut'
    display_options:
      fields:
        name:
          label: Auteur
        changed:
          label: 'Mis à jour'
        operations:
          label: Actions
      pager:
        options:
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      exposed_form:
        options:
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
      filters:
        langcode:
          expose:
            label: Langue
  page_unapproved:
    display_options:
      fields:
        name:
          label: Auteur
        changed:
          label: 'Mis à jour'
        operations:
          label: Actions
      filters:
        langcode:
          expose:
            label: Langue
