display:
  default:
    display_title: 默认
    display_options:
      fields:
        title:
          label: 标题
        type:
          label: 内容类型
        name:
          label: 作者
        changed:
          label: 已更新
        operations:
          label: 操作
      pager:
        options:
          tags:
            first: '« 首页'
            last: '末页 »'
          expose:
            items_per_page_label: 每页条目数
            items_per_page_options_all_label: '- 全部 -'
            offset_label: 偏移量
      exposed_form:
        options:
          reset_button_label: 重置
          exposed_sorts_label: 排序依据
          sort_asc_label: 升序
          sort_desc_label: 降序
      filters:
        title:
          expose:
            label: 标题
        type:
          expose:
            label: 内容类型
        langcode:
          expose:
            label: 语言
