label: 媒体
display:
  default:
    display_title: 默认
    display_options:
      title: 媒体
      fields:
        media_bulk_form:
          action_title: 动作
        bundle:
          label: 类型
        uid:
          label: 作者
        status:
          label: 状态
          settings:
            format_custom_false: 未发布
            format_custom_true: 已发布
        changed:
          label: 已更新
        operations:
          label: 操作
      pager:
        options:
          tags:
            first: '« 首页'
            last: '末页 »'
          expose:
            items_per_page_label: 每页条目数
            items_per_page_options_all_label: '- 全部 -'
            offset_label: 偏移量
      exposed_form:
        options:
          reset_button_label: 重置
          exposed_sorts_label: 排序依据
          sort_asc_label: 升序
          sort_desc_label: 降序
      filters:
        bundle:
          expose:
            label: 类型
        status:
          group_info:
            label: 发布状态
            group_items:
              1:
                title: 已发布
              2:
                title: 未发布
        langcode:
          expose:
            label: 语言
  media_page_list:
    display_title: 媒体
    display_options:
      menu:
        title: 媒体
