display:
  default:
    display_title: 'Mặc định'
    display_options:
      fields:
        comment_bulk_form:
          action_title: 'Thao tác'
        name:
          label: 'Tác giả'
        changed:
          label: 'Đã cập nhật'
        operations:
          label: 'Thao tác'
      pager:
        options:
          expose:
            items_per_page_label: 'Số mục trên một trang'
            items_per_page_options_all_label: '- Tất cả -'
            offset_label: 'Độ dịch'
      exposed_form:
        options:
          reset_button_label: 'Thiết lập lại'
          exposed_sorts_label: 'Sắp xếp theo'
          sort_asc_label: 'Tăng dần'
          sort_desc_label: 'Giảm dần'
      filters:
        langcode:
          expose:
            label: 'Ngôn ngữ'
  page_unapproved:
    display_options:
      fields:
        comment_bulk_form:
          action_title: 'Thao tác'
        name:
          label: 'Tác giả'
        changed:
          label: 'Đã cập nhật'
        operations:
          label: 'Thao tác'
      filters:
        langcode:
          expose:
            label: 'Ngôn ngữ'
