display:
  default:
    display_title: 'Mặc định'
    display_options:
      fields:
        type:
          label: Kiểu
        timestamp:
          label: 'Ngày tháng'
        message:
          label: 'Thông điệp'
        name:
          label: 'Người dùng'
        link:
          label: 'Thao tác'
      pager:
        options:
          expose:
            items_per_page_label: 'Số mục trên một trang'
            items_per_page_options_all_label: '- Tất cả -'
            offset_label: 'Độ dịch'
      exposed_form:
        options:
          reset_button_label: 'Thiết lập lại'
          exposed_sorts_label: 'Sắp xếp theo'
          sort_asc_label: 'Tăng dần'
          sort_desc_label: 'Giảm dần'
      filters:
        type:
          expose:
            label: Kiểu
  page:
    display_title: Trang
