display:
  default:
    display_title: Chính
    display_options:
      exposed_form:
        options:
          reset_button_label: 'Thiết lập lại'
          exposed_sorts_label: 'Sắp xếp theo'
          sort_asc_label: 'Tăng dần'
          sort_desc_label: 'Giảm dần'
      pager:
        options:
          expose:
            items_per_page_label: 'Số mục trên một trang'
            items_per_page_options_all_label: '- Tất cả -'
            offset_label: 'Độ dịch'
      fields:
        code:
          label: Mã
        operations:
          label: 'Thao tác'
      filters:
        code:
          expose:
            label: Mã
      arguments:
        promotion_id:
          exception:
            title: 'Tất cả'
  page_1:
    display_title: Trang
