display:
  default:
    display_title: Chính
    display_options:
      fields:
        is_default:
          label: 'Mặc định'
        name:
          label: Tên
        changed:
          label: 'Đã cập nhật'
        type:
          label: Kiểu
        operations:
          label: 'Thao tác'
      pager:
        options:
          expose:
            items_per_page_label: 'Số mục trên một trang'
            items_per_page_options_all_label: '- Tất cả -'
            offset_label: 'Độ dịch'
      exposed_form:
        options:
          submit_button: 'Áp dụng'
          reset_button_label: 'Thiết lập lại'
          exposed_sorts_label: 'Sắp xếp theo'
          sort_asc_label: 'Tăng dần'
          sort_desc_label: 'Giảm dần'
      filters:
        type:
          expose:
            label: Kiểu
  page_1:
    display_title: Trang
