description: 'Ez a kérdés vizsgálja, hogy vajon ember-e a látogató, valamint megelőzi az automatikus kéretlen üzenetek beküldését.'
wrong_captcha_response_message: 'A CAPTCHA feladatra adott válasz helytelen volt.'
