display:
  default:
    display_title: Mester
    display_options:
      exposed_form:
        options:
          submit_button: Alkalmaz
          reset_button_label: Alaphelyzet
          exposed_sorts_label: Rendezés
          sort_asc_label: Növ
          sort_desc_label: Csökk
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« Első'
            last: 'Utolsó »'
          expose:
            items_per_page_label: 'Elemek száma oldalanként'
            items_per_page_options_all_label: '– Mind –'
            offset_label: Eltolás
      fields:
        nid:
          separator: ', '
        delta:
          format_plural_string: !!binary MQNAY291bnQ=
        nothing:
          alter:
            text: Szerkesztés
        nothing_1:
          alter:
            text: Törlés
        title:
          label: Cím
          separator: ', '
        sp_dynamic:
          separator: ', '
        sp_dynamic_1:
          separator: ', '
        dropbutton:
          label: Műveletek
      filters:
        title:
          expose:
            label: Cím
  block_1:
    display_title: Blokk
