settings:
  default_submit_button_label: Beküldés
  default_reset_button_label: Alaphelyzet
  default_delete_button_label: Törlés
  default_form_access_denied_message: 'Be kell jelentkezni az űrlap eléréséhez.'
  default_form_required_label: 'Kötelezően kitöltendő mezőt jelöl'
  default_wizard_prev_button_label: '< Előző'
  default_wizard_next_button_label: 'Következő >'
  default_wizard_start_label: Kezdete
  default_wizard_confirmation_label: Kész
  default_wizard_toggle_show_label: 'Összes megjelenítése'
  default_preview_next_button_label: Előnézet
  default_preview_prev_button_label: '< Előző'
  default_preview_label: Előnézet
  default_draft_button_label: 'Piszkozat mentése'
  default_draft_saved_message: 'A beküldés mentése megtörtént. Későbbi látogatás során a jelenlegi értékeket fogja megjeleníteni.'
  default_confirmation_message: '[webform:title] űrlap beküldése megtörtént.'
  default_confirmation_back_label: 'Vissza az űrlaphoz'
  default_submission_label: '[webform_submission:submitted-to] űrlap #[webform_submission:serial] beküldése'
  default_previous_submission_message: 'Jelen felhasználó korábban már beküldte ezt az űrlapot. <a href="#">Megtekintés</a>'
  default_previous_submissions_message: 'Jelen felhasználó korábban már beküldte ezt az űrlapot. <a href="#">Megtekintés</a>'
  dialog_options:
    narrow:
      title: Keskeny
    normal:
      title: Általános
    wide:
      title: Széles
element:
  empty_message: '{Üres}'
  default_more_title: Több
  default_section_title_tag: h2
file:
  file_private_redirect_message: 'Be kell jelentkezni a feltöltött fájl eléréséhez.'
mail:
  default_from_name: '[site:name]'
