display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
      fields:
        title:
          label: หัวข้อ
      arguments:
        order_item_id:
          exception:
            title: ทั้งหมด
