display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
      arguments:
        uid:
          exception:
            title: ทั้งหมด
        type:
          exception:
            title: ทั้งหมด
        status:
          exception:
            title: ทั้งหมด
