display:
  default:
    display_options:
      fields:
        is_default:
          label: Default
        name:
          label: Name
        type:
          label: ประเภท
        operations:
          label: Operations
      exposed_form:
        options:
          reset_button_label: Reset
      filters:
        type:
          expose:
            label: ประเภท
