display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
      fields:
        title:
          label: หัวข้อ
        type:
          label: ประเภท
        status:
          label: สถานะ
        operations:
          label: Operations
      filters:
        type:
          expose:
            label: ประเภท
        title:
          expose:
            label: หัวข้อ
