display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
      pager:
        options:
          tags:
            first: '« first'
            last: 'last »'
      fields:
        code:
          label: รหัส
        operations:
          label: Operations
      filters:
        code:
          expose:
            label: รหัส
      arguments:
        promotion_id:
          exception:
            title: ทั้งหมด
