display:
  default:
    display_title: Default
    display_options:
      fields:
        type:
          label: ประเภท
        timestamp:
          label: วันที่
        message:
          label: ข้อความ
        link:
          label: Operations
      exposed_form:
        options:
          reset_button_label: Reset
      filters:
        type:
          expose:
            label: ประเภท
