display:
  default:
    display_title: Default
    display_options:
      fields:
        title:
          label: หัวข้อ
        type:
          label: ชนิดของเนื้อหา
        status:
          label: สถานะ
        operations:
          label: Operations
      pager:
        options:
          tags:
            first: '« first'
            last: 'last »'
      exposed_form:
        options:
          reset_button_label: Reset
      filters:
        title:
          expose:
            label: หัวข้อ
        type:
          expose:
            label: ชนิดของเนื้อหา
        status:
          expose:
            label: สถานะ
