display:
  default:
    display_title: Default
    display_options:
      title: สื่อ
      fields:
        media_bulk_form:
          action_title: แอคชั่น
      exposed_form:
        options:
          reset_button_label: Reset
      filters:
        name:
          expose:
            label: Name
  page:
    display_options:
      fields:
        media_bulk_form:
          action_title: แอคชั่น
        edit_media:
          text: แก้ไข
        delete_media:
          text: ลบ
  widget:
    display_title: วิดเจ็ต
    display_options:
      arguments:
        bundle:
          exception:
            title: ทั้งหมด
      filters:
        name:
          expose:
            label: Name
  widget_table:
    display_options:
      fields:
        name:
          label: Name
      arguments:
        bundle:
          exception:
            title: ทั้งหมด
      filters:
        name:
          expose:
            label: Name
