display:
  default:
    display_title: Default
    display_options:
      fields:
        comment_bulk_form:
          action_title: แอคชั่น
        operations:
          label: Operations
      exposed_form:
        options:
          reset_button_label: Reset
  page_unapproved:
    display_options:
      fields:
        comment_bulk_form:
          action_title: แอคชั่น
        operations:
          label: Operations
