display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
      fields:
        placed:
          label: วันที่
        type:
          label: ประเภท
        operations:
          label: Operations
      filters:
        type:
          expose:
            label: ประเภท
